# test_regression.py — 50-game regression (1 test, all games in one sim)
# Instance name in top.v: u_mlp_ip (verified from top.v source)

import cocotb
from cocotb.triggers import ClockCycles

from uart_helpers import (
    init_dut, uart_send_packet, uart_recv_response,
    model_outputs_to_stub_vals,
)
import csv
import os
import numpy as np

# Absolute path to project root (two levels up from phase6_sim/cocotb/)
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))


def _vec(name):
    return os.path.join(_PROJECT_ROOT, 'phase6_sim', 'test_vectors', name)


@cocotb.test()
async def test_50_game_regression(dut):
    """
    Run all 50 test games through the complete simulation and verify
    FPGA outputs match Python quantized model predictions.

    Pass criteria:
    - Win byte agreement >= 98% (|hw_win_u8 - exp_win_u8| <= 2 counts vs Python model)
    - Spread MAE <= 0.5 points (vs Python model)
    - Status OK rate = 100% (no framing errors)
    """
    await init_dut(dut)

    # Load test vectors (generated by run_sim.py step 1)
    inputs   = list(csv.DictReader(open(_vec('input_games.csv'))))
    expected = list(csv.DictReader(open(_vec('expected_outputs.csv'))))
    assert len(inputs) == 50 and len(expected) == 50, \
        f"Expected 50 games, got inputs={len(inputs)} expected={len(expected)}"

    results = []

    for i, (inp, exp) in enumerate(zip(inputs, expected)):
        feature_bytes = [int(inp[f'feature_{j}']) for j in range(21)]
        exp_win_u8    = int(exp['win_uint8'])
        exp_spread_i8 = int(exp['spread_int8'])
        py_win_prob   = float(exp['win_prob_float'])
        py_spread     = float(exp['spread_float'])

        # Inject expected outputs into stub via hierarchy access
        # Instance name is u_mlp_ip (top.v: myproject u_mlp_ip (...))
        win_18bit, spread_32bit, _, _ = model_outputs_to_stub_vals(
            py_win_prob, py_spread
        )
        dut.u_mlp_ip.win_val.value    = win_18bit
        dut.u_mlp_ip.spread_val.value = spread_32bit

        # Concurrent recv/send — start recv BEFORE send to avoid missing fast response
        recv_task = cocotb.start_soon(
            uart_recv_response(dut.uart_txd, timeout_clks=300_000)
        )
        await uart_send_packet(dut.uart_rxd, feature_bytes)
        sof, hw_win, hw_spread_raw, status = await recv_task

        hw_spread = hw_spread_raw if hw_spread_raw < 128 else hw_spread_raw - 256

        win_delta    = abs(hw_win - exp_win_u8)
        spread_delta = abs(hw_spread - exp_spread_i8)
        status_ok    = (status == 0x00)
        win_agree    = (win_delta <= 2)

        results.append({
            'game_idx':     i,
            'home_team':    inp.get('home_team', ''),
            'away_team':    inp.get('away_team', ''),
            'py_win':       py_win_prob,
            'hw_win':       hw_win / 256.0,
            'win_delta':    win_delta,
            'py_spread':    py_spread,
            'hw_spread':    hw_spread,
            'spread_delta': spread_delta,
            'status_ok':    status_ok,
            'win_agree':    win_agree,
        })

        if i % 10 == 0:
            cocotb.log.info(
                f"Game {i}/50: {inp.get('home_team','?')} vs "
                f"{inp.get('away_team','?')} — "
                f"win {hw_win/256:.1%} vs {py_win_prob:.1%}, "
                f"spread {hw_spread:+d} vs {py_spread:+.1f}"
            )

    # Compute pass metrics
    win_agreement  = sum(r['win_agree']   for r in results) / 50
    spread_mae     = np.mean([r['spread_delta'] for r in results])
    status_ok_rate = sum(r['status_ok']   for r in results) / 50

    cocotb.log.info(f"\n{'='*50}")
    cocotb.log.info(f"REGRESSION RESULTS — 50 NFL Games")
    cocotb.log.info(f"Win agreement (±2 counts): {win_agreement:.1%} "
                    f"(threshold: ≥98%)")
    cocotb.log.info(f"Spread MAE vs Python:      {spread_mae:.2f} pts "
                    f"(threshold: ≤0.5)")
    cocotb.log.info(f"Status OK rate:            {status_ok_rate:.1%} "
                    f"(threshold: 100%)")
    cocotb.log.info(f"{'='*50}")

    # Write sim_outputs.csv for pytest
    with open(_vec('sim_outputs.csv'), 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=results[0].keys())
        writer.writeheader()
        writer.writerows(results)

    assert win_agreement  >= 0.98, f"Win agreement {win_agreement:.1%} < 98%"
    assert spread_mae     <= 0.5,  f"Spread MAE {spread_mae:.2f} > 0.5 pts"
    assert status_ok_rate == 1.0,  "Framing errors detected — status not 100% OK"
