-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer11_cpy2_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer11_cpy2_empty_n : IN STD_LOGIC;
    layer11_cpy2_read : OUT STD_LOGIC;
    layer11_cpy2_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer11_cpy2_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer10_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    layer10_out_TVALID : OUT STD_LOGIC;
    layer10_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config10_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_B7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110111";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110111";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer11_cpy2_blk_n : STD_LOGIC;
    signal layer10_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_fu_205_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_reg_556 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_123_reg_561 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_93_reg_566 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_94_reg_571 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_95_reg_576 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_96_reg_581 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_97_reg_586 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_98_reg_591 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_99_reg_596 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_100_reg_601 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_101_reg_606 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_102_reg_611 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_103_reg_616 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_104_reg_621 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_105_reg_626 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_106_reg_631 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_107_reg_636 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_108_reg_641 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_109_reg_646 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_110_reg_651 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_111_reg_656 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_112_reg_661 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_113_reg_666 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_114_reg_671 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_115_reg_676 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_116_reg_681 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_117_reg_686 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_118_reg_691 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_119_reg_696 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_120_reg_701 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_121_reg_706 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_122_reg_711 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call35 : BOOLEAN;
    signal regslice_both_layer10_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal layer10_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal layer10_out_TVALID_int_regslice : STD_LOGIC;
    signal layer10_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer10_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (7 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167 : component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start,
        ap_done => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done,
        ap_idle => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_idle,
        ap_ready => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready,
        data_0_val => data_reg_556,
        data_1_val => data_123_reg_561,
        data_2_val => data_93_reg_566,
        data_3_val => data_94_reg_571,
        data_4_val => data_95_reg_576,
        data_5_val => data_96_reg_581,
        data_6_val => data_97_reg_586,
        data_7_val => data_98_reg_591,
        data_8_val => data_99_reg_596,
        data_9_val => data_100_reg_601,
        data_10_val => data_101_reg_606,
        data_11_val => data_102_reg_611,
        data_12_val => data_103_reg_616,
        data_13_val => data_104_reg_621,
        data_14_val => data_105_reg_626,
        data_15_val => data_106_reg_631,
        data_16_val => data_107_reg_636,
        data_17_val => data_108_reg_641,
        data_18_val => data_109_reg_646,
        data_19_val => data_110_reg_651,
        data_20_val => data_111_reg_656,
        data_21_val => data_112_reg_661,
        data_22_val => data_113_reg_666,
        data_23_val => data_114_reg_671,
        data_24_val => data_115_reg_676,
        data_25_val => data_116_reg_681,
        data_26_val => data_117_reg_686,
        data_27_val => data_118_reg_691,
        data_28_val => data_119_reg_696,
        data_29_val => data_120_reg_701,
        data_30_val => data_121_reg_706,
        data_31_val => data_122_reg_711,
        ap_return => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return);

    regslice_both_layer10_out_U : component myproject_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer10_out_TDATA_int_regslice,
        vld_in => layer10_out_TVALID_int_regslice,
        ack_in => layer10_out_TREADY_int_regslice,
        data_out => layer10_out_TDATA,
        vld_out => regslice_both_layer10_out_U_vld_out,
        ack_out => layer10_out_TREADY,
        apdone_blk => regslice_both_layer10_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call35) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_100_reg_601 <= layer11_cpy2_dout(79 downto 72);
                data_101_reg_606 <= layer11_cpy2_dout(87 downto 80);
                data_102_reg_611 <= layer11_cpy2_dout(95 downto 88);
                data_103_reg_616 <= layer11_cpy2_dout(103 downto 96);
                data_104_reg_621 <= layer11_cpy2_dout(111 downto 104);
                data_105_reg_626 <= layer11_cpy2_dout(119 downto 112);
                data_106_reg_631 <= layer11_cpy2_dout(127 downto 120);
                data_107_reg_636 <= layer11_cpy2_dout(135 downto 128);
                data_108_reg_641 <= layer11_cpy2_dout(143 downto 136);
                data_109_reg_646 <= layer11_cpy2_dout(151 downto 144);
                data_110_reg_651 <= layer11_cpy2_dout(159 downto 152);
                data_111_reg_656 <= layer11_cpy2_dout(167 downto 160);
                data_112_reg_661 <= layer11_cpy2_dout(175 downto 168);
                data_113_reg_666 <= layer11_cpy2_dout(183 downto 176);
                data_114_reg_671 <= layer11_cpy2_dout(191 downto 184);
                data_115_reg_676 <= layer11_cpy2_dout(199 downto 192);
                data_116_reg_681 <= layer11_cpy2_dout(207 downto 200);
                data_117_reg_686 <= layer11_cpy2_dout(215 downto 208);
                data_118_reg_691 <= layer11_cpy2_dout(223 downto 216);
                data_119_reg_696 <= layer11_cpy2_dout(231 downto 224);
                data_120_reg_701 <= layer11_cpy2_dout(239 downto 232);
                data_121_reg_706 <= layer11_cpy2_dout(247 downto 240);
                data_122_reg_711 <= layer11_cpy2_dout(255 downto 248);
                data_123_reg_561 <= layer11_cpy2_dout(15 downto 8);
                data_93_reg_566 <= layer11_cpy2_dout(23 downto 16);
                data_94_reg_571 <= layer11_cpy2_dout(31 downto 24);
                data_95_reg_576 <= layer11_cpy2_dout(39 downto 32);
                data_96_reg_581 <= layer11_cpy2_dout(47 downto 40);
                data_97_reg_586 <= layer11_cpy2_dout(55 downto 48);
                data_98_reg_591 <= layer11_cpy2_dout(63 downto 56);
                data_99_reg_596 <= layer11_cpy2_dout(71 downto 64);
                data_reg_556 <= data_fu_205_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_block_state1, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done, ap_block_state3, layer10_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((layer10_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done, layer10_out_TREADY_int_regslice)
    begin
        if (((layer10_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, layer11_cpy2_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (layer11_cpy2_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call35_assign_proc : process(ap_start, ap_done_reg, layer11_cpy2_empty_n)
    begin
                ap_block_state1_ignore_call35 <= ((ap_start = ap_const_logic_0) or (layer11_cpy2_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(regslice_both_layer10_out_U_apdone_blk, layer10_out_TREADY_int_regslice)
    begin
                ap_block_state3 <= ((layer10_out_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_layer10_out_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    data_fu_205_p1 <= layer11_cpy2_dout(8 - 1 downto 0);
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg;

    layer10_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, layer10_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer10_out_TDATA_blk_n <= layer10_out_TREADY_int_regslice;
        else 
            layer10_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer10_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return),32));

    layer10_out_TVALID <= regslice_both_layer10_out_U_vld_out;

    layer10_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done, layer10_out_TREADY_int_regslice)
    begin
        if ((not(((layer10_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer10_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer10_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    layer11_cpy2_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer11_cpy2_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer11_cpy2_blk_n <= layer11_cpy2_empty_n;
        else 
            layer11_cpy2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer11_cpy2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer11_cpy2_read <= ap_const_logic_1;
        else 
            layer11_cpy2_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
