-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_sigmoid_ap_fixed_32_16_5_3_0_ap_fixed_18_6_5_3_0_sigmoid_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_blk_n : OUT STD_LOGIC );
end;


architecture behav of myproject_sigmoid_ap_fixed_32_16_5_3_0_ap_fixed_18_6_5_3_0_sigmoid_config9_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv23_200 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000001000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal sigmoid_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer8_out_read_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_3_reg_202 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln119_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_209 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln117_1_fu_158_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln117_1_reg_214 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_219 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln125_fu_184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sigmoid_table_ce0_local : STD_LOGIC;
    signal trunc_ln119_fu_85_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_89_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln119_fu_110_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_fu_103_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln119_fu_115_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal data_round_fu_121_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln116_fu_128_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal index_fu_132_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_1_fu_142_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln117_fu_138_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal index_1_fu_150_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln123_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_2_fu_177_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_sigmoid_ap_fixed_32_16_5_3_0_ap_fixed_18_6_5_3_0_sigmoid_config9_s_sigmoid_taibs IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    sigmoid_table_U : component myproject_sigmoid_ap_fixed_32_16_5_3_0_ap_fixed_18_6_5_3_0_sigmoid_config9_s_sigmoid_taibs
    generic map (
        DataWidth => 10,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_table_address0,
        ce0 => sigmoid_table_ce0_local,
        q0 => sigmoid_table_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln119_reg_209 <= icmp_ln119_fu_97_p2;
                layer8_out_read_reg_197 <= layer8_out_dout;
                tmp_3_reg_202 <= layer8_out_dout(31 downto 10);
                tmp_4_reg_219 <= index_1_fu_150_p3(21 downto 10);
                trunc_ln117_1_reg_214 <= trunc_ln117_1_fu_158_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln119_fu_110_p2 <= std_logic_vector(unsigned(tmp_3_reg_202) + unsigned(ap_const_lv22_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_block_state1_pp0_stage0_iter0, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(layer8_out_empty_n)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (layer8_out_empty_n = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to2)
    begin
        if ((ap_idle_pp0_0to2 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= (sigmoid_table_q0 & ap_const_lv2_0);
    data_round_fu_121_p3 <= 
        select_ln119_fu_115_p3 when (tmp_fu_103_p3(0) = '1') else 
        tmp_3_reg_202;
    icmp_ln119_fu_97_p2 <= "0" when (tmp_2_fu_89_p3 = ap_const_lv16_0) else "1";
    icmp_ln123_fu_172_p2 <= "0" when (tmp_4_reg_219 = ap_const_lv12_0) else "1";
    index_1_fu_150_p3 <= 
        ap_const_lv22_0 when (tmp_1_fu_142_p3(0) = '1') else 
        trunc_ln117_fu_138_p1;
    index_2_fu_177_p3 <= 
        ap_const_lv10_3FF when (icmp_ln123_fu_172_p2(0) = '1') else 
        trunc_ln117_1_reg_214;
    index_fu_132_p2 <= std_logic_vector(signed(sext_ln116_fu_128_p1) + signed(ap_const_lv23_200));

    layer8_out_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, layer8_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln119_fu_115_p3 <= 
        add_ln119_fu_110_p2 when (icmp_ln119_reg_209(0) = '1') else 
        tmp_3_reg_202;
        sext_ln116_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_round_fu_121_p3),23));

    sigmoid_table_address0 <= zext_ln125_fu_184_p1(10 - 1 downto 0);

    sigmoid_table_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            sigmoid_table_ce0_local <= ap_const_logic_1;
        else 
            sigmoid_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_142_p3 <= index_fu_132_p2(22 downto 22);
    tmp_2_fu_89_p3 <= (trunc_ln119_fu_85_p1 & ap_const_lv6_0);
    tmp_fu_103_p3 <= layer8_out_read_reg_197(31 downto 31);
    trunc_ln117_1_fu_158_p1 <= index_1_fu_150_p3(10 - 1 downto 0);
    trunc_ln117_fu_138_p1 <= index_fu_132_p2(22 - 1 downto 0);
    trunc_ln119_fu_85_p1 <= layer8_out_dout(10 - 1 downto 0);
    zext_ln125_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_2_fu_177_p3),64));
end behav;
