-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config2_s_outidx_Rbkb is 
    generic(
             DataWidth     : integer := 3; 
             AddressWidth     : integer := 8; 
             AddressRange    : integer := 168
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config2_s_outidx_Rbkb is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000", 1 => "000", 2 => "000", 3 => "000", 
    4 => "000", 5 => "000", 6 => "000", 7 => "000", 
    8 => "000", 9 => "000", 10 => "000", 11 => "000", 
    12 => "000", 13 => "000", 14 => "000", 15 => "000", 
    16 => "000", 17 => "000", 18 => "000", 19 => "000", 
    20 => "000", 21 => "001", 22 => "001", 23 => "001", 
    24 => "001", 25 => "001", 26 => "001", 27 => "001", 
    28 => "001", 29 => "001", 30 => "001", 31 => "001", 
    32 => "001", 33 => "001", 34 => "001", 35 => "001", 
    36 => "001", 37 => "001", 38 => "001", 39 => "001", 
    40 => "001", 41 => "001", 42 => "010", 43 => "010", 
    44 => "010", 45 => "010", 46 => "010", 47 => "010", 
    48 => "010", 49 => "010", 50 => "010", 51 => "010", 
    52 => "010", 53 => "010", 54 => "010", 55 => "010", 
    56 => "010", 57 => "010", 58 => "010", 59 => "010", 
    60 => "010", 61 => "010", 62 => "010", 63 => "011", 
    64 => "011", 65 => "011", 66 => "011", 67 => "011", 
    68 => "011", 69 => "011", 70 => "011", 71 => "011", 
    72 => "011", 73 => "011", 74 => "011", 75 => "011", 
    76 => "011", 77 => "011", 78 => "011", 79 => "011", 
    80 => "011", 81 => "011", 82 => "011", 83 => "011", 
    84 => "100", 85 => "100", 86 => "100", 87 => "100", 
    88 => "100", 89 => "100", 90 => "100", 91 => "100", 
    92 => "100", 93 => "100", 94 => "100", 95 => "100", 
    96 => "100", 97 => "100", 98 => "100", 99 => "100", 
    100 => "100", 101 => "100", 102 => "100", 103 => "100", 
    104 => "100", 105 => "101", 106 => "101", 107 => "101", 
    108 => "101", 109 => "101", 110 => "101", 111 => "101", 
    112 => "101", 113 => "101", 114 => "101", 115 => "101", 
    116 => "101", 117 => "101", 118 => "101", 119 => "101", 
    120 => "101", 121 => "101", 122 => "101", 123 => "101", 
    124 => "101", 125 => "101", 126 => "110", 127 => "110", 
    128 => "110", 129 => "110", 130 => "110", 131 => "110", 
    132 => "110", 133 => "110", 134 => "110", 135 => "110", 
    136 => "110", 137 => "110", 138 => "110", 139 => "110", 
    140 => "110", 141 => "110", 142 => "110", 143 => "110", 
    144 => "110", 145 => "110", 146 => "110", 147 => "111", 
    148 => "111", 149 => "111", 150 => "111", 151 => "111", 
    152 => "111", 153 => "111", 154 => "111", 155 => "111", 
    156 => "111", 157 => "111", 158 => "111", 159 => "111", 
    160 => "111", 161 => "111", 162 => "111", 163 => "111", 
    164 => "111", 165 => "111", 166 => "111", 167 => "111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

