// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer11_cpy1_dout,
        layer11_cpy1_empty_n,
        layer11_cpy1_read,
        layer11_cpy1_num_data_valid,
        layer11_cpy1_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] layer11_cpy1_dout;
input   layer11_cpy1_empty_n;
output   layer11_cpy1_read;
input  [1:0] layer11_cpy1_num_data_valid;
input  [1:0] layer11_cpy1_fifo_cap;
output  [31:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer11_cpy1_read;
reg layer8_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer11_cpy1_blk_n;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [7:0] data_fu_199_p1;
reg   [7:0] data_reg_550;
reg    ap_block_state1;
reg   [7:0] data_93_reg_555;
reg   [7:0] data_63_reg_560;
reg   [7:0] data_64_reg_565;
reg   [7:0] data_65_reg_570;
reg   [7:0] data_66_reg_575;
reg   [7:0] data_67_reg_580;
reg   [7:0] data_68_reg_585;
reg   [7:0] data_69_reg_590;
reg   [7:0] data_70_reg_595;
reg   [7:0] data_71_reg_600;
reg   [7:0] data_72_reg_605;
reg   [7:0] data_73_reg_610;
reg   [7:0] data_74_reg_615;
reg   [7:0] data_75_reg_620;
reg   [7:0] data_76_reg_625;
reg   [7:0] data_77_reg_630;
reg   [7:0] data_78_reg_635;
reg   [7:0] data_79_reg_640;
reg   [7:0] data_80_reg_645;
reg   [7:0] data_81_reg_650;
reg   [7:0] data_82_reg_655;
reg   [7:0] data_83_reg_660;
reg   [7:0] data_84_reg_665;
reg   [7:0] data_85_reg_670;
reg   [7:0] data_86_reg_675;
reg   [7:0] data_87_reg_680;
reg   [7:0] data_88_reg_685;
reg   [7:0] data_89_reg_690;
reg   [7:0] data_90_reg_695;
reg   [7:0] data_91_reg_700;
reg   [7:0] data_92_reg_705;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_ready;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_return;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg;
reg    ap_block_state1_ignore_call35;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg = 1'b0;
end

myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_ready),
    .data_0_val(data_reg_550),
    .data_1_val(data_93_reg_555),
    .data_2_val(data_63_reg_560),
    .data_3_val(data_64_reg_565),
    .data_4_val(data_65_reg_570),
    .data_5_val(data_66_reg_575),
    .data_6_val(data_67_reg_580),
    .data_7_val(data_68_reg_585),
    .data_8_val(data_69_reg_590),
    .data_9_val(data_70_reg_595),
    .data_10_val(data_71_reg_600),
    .data_11_val(data_72_reg_605),
    .data_12_val(data_73_reg_610),
    .data_13_val(data_74_reg_615),
    .data_14_val(data_75_reg_620),
    .data_15_val(data_76_reg_625),
    .data_16_val(data_77_reg_630),
    .data_17_val(data_78_reg_635),
    .data_18_val(data_79_reg_640),
    .data_19_val(data_80_reg_645),
    .data_20_val(data_81_reg_650),
    .data_21_val(data_82_reg_655),
    .data_22_val(data_83_reg_660),
    .data_23_val(data_84_reg_665),
    .data_24_val(data_85_reg_670),
    .data_25_val(data_86_reg_675),
    .data_26_val(data_87_reg_680),
    .data_27_val(data_88_reg_685),
    .data_28_val(data_89_reg_690),
    .data_29_val(data_90_reg_695),
    .data_30_val(data_91_reg_700),
    .data_31_val(data_92_reg_705),
    .ap_return(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call35) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_63_reg_560 <= {{layer11_cpy1_dout[23:16]}};
        data_64_reg_565 <= {{layer11_cpy1_dout[31:24]}};
        data_65_reg_570 <= {{layer11_cpy1_dout[39:32]}};
        data_66_reg_575 <= {{layer11_cpy1_dout[47:40]}};
        data_67_reg_580 <= {{layer11_cpy1_dout[55:48]}};
        data_68_reg_585 <= {{layer11_cpy1_dout[63:56]}};
        data_69_reg_590 <= {{layer11_cpy1_dout[71:64]}};
        data_70_reg_595 <= {{layer11_cpy1_dout[79:72]}};
        data_71_reg_600 <= {{layer11_cpy1_dout[87:80]}};
        data_72_reg_605 <= {{layer11_cpy1_dout[95:88]}};
        data_73_reg_610 <= {{layer11_cpy1_dout[103:96]}};
        data_74_reg_615 <= {{layer11_cpy1_dout[111:104]}};
        data_75_reg_620 <= {{layer11_cpy1_dout[119:112]}};
        data_76_reg_625 <= {{layer11_cpy1_dout[127:120]}};
        data_77_reg_630 <= {{layer11_cpy1_dout[135:128]}};
        data_78_reg_635 <= {{layer11_cpy1_dout[143:136]}};
        data_79_reg_640 <= {{layer11_cpy1_dout[151:144]}};
        data_80_reg_645 <= {{layer11_cpy1_dout[159:152]}};
        data_81_reg_650 <= {{layer11_cpy1_dout[167:160]}};
        data_82_reg_655 <= {{layer11_cpy1_dout[175:168]}};
        data_83_reg_660 <= {{layer11_cpy1_dout[183:176]}};
        data_84_reg_665 <= {{layer11_cpy1_dout[191:184]}};
        data_85_reg_670 <= {{layer11_cpy1_dout[199:192]}};
        data_86_reg_675 <= {{layer11_cpy1_dout[207:200]}};
        data_87_reg_680 <= {{layer11_cpy1_dout[215:208]}};
        data_88_reg_685 <= {{layer11_cpy1_dout[223:216]}};
        data_89_reg_690 <= {{layer11_cpy1_dout[231:224]}};
        data_90_reg_695 <= {{layer11_cpy1_dout[239:232]}};
        data_91_reg_700 <= {{layer11_cpy1_dout[247:240]}};
        data_92_reg_705 <= {{layer11_cpy1_dout[255:248]}};
        data_93_reg_555 <= {{layer11_cpy1_dout[15:8]}};
        data_reg_550 <= data_fu_199_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_cpy1_blk_n = layer11_cpy1_empty_n;
    end else begin
        layer11_cpy1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_cpy1_read = 1'b1;
    end else begin
        layer11_cpy1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((layer8_out_full_n == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer11_cpy1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call35 = ((real_start == 1'b0) | (layer11_cpy1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_fu_199_p1 = layer11_cpy1_dout[7:0];

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_start_reg;

assign layer8_out_din = $signed(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_fu_161_ap_return);

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config8_s
