// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer7_out_dout,
        layer7_out_empty_n,
        layer7_out_read,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] layer7_out_dout;
input   layer7_out_empty_n;
output   layer7_out_read;
output  [31:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer7_out_read;
reg layer8_out_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln47_fu_144_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln47_reg_206;
reg   [0:0] icmp_ln47_reg_206_pp0_iter2_reg;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] w8_address0;
wire   [11:0] w8_q0;
reg    layer7_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer8_out_blk_n;
reg   [4:0] ir_reg_105;
reg   [17:0] empty_reg_119;
wire   [4:0] w_index_fu_138_p2;
reg   [4:0] w_index_reg_201;
reg   [0:0] icmp_ln47_reg_206_pp0_iter1_reg;
reg  signed [7:0] a_reg_210;
reg  signed [11:0] w_reg_215;
reg   [15:0] trunc_ln_reg_220;
wire   [17:0] x_fu_175_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [4:0] ap_phi_mux_ir_phi_fu_109_p6;
wire   [63:0] zext_ln47_fu_133_p1;
reg    ap_block_pp0_stage0_01001;
reg    w8_ce0_local;
wire   [19:0] mul_ln73_fu_156_p2;
wire  signed [17:0] sext_ln59_fu_172_p1;
wire   [21:0] shl_ln_fu_181_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to2;
reg    ap_reset_init_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_79;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s_w8_ROM_NP_Bhbi #(
    .DataWidth( 12 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
w8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w8_address0),
    .ce0(w8_ce0_local),
    .q0(w8_q0)
);

myproject_mul_12s_8s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 20 ))
mul_12s_8s_20_1_1_U330(
    .din0(w_reg_215),
    .din1(a_reg_210),
    .dout(mul_ln73_fu_156_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln47_reg_206_pp0_iter2_reg == 1'd0))) begin
        empty_reg_119 <= x_fu_175_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln47_reg_206_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        empty_reg_119 <= 18'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln47_reg_206 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ir_reg_105 <= w_index_reg_201;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln47_reg_206 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ir_reg_105 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_210 <= layer7_out_dout;
        icmp_ln47_reg_206 <= icmp_ln47_fu_144_p2;
        icmp_ln47_reg_206_pp0_iter1_reg <= icmp_ln47_reg_206;
        w_reg_215 <= w8_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln47_reg_206_pp0_iter2_reg <= icmp_ln47_reg_206_pp0_iter1_reg;
        trunc_ln_reg_220 <= {{mul_ln73_fu_156_p2[19:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_201 <= w_index_fu_138_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln47_reg_206_pp0_iter2_reg == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_79)) begin
        if ((icmp_ln47_reg_206 == 1'd1)) begin
            ap_phi_mux_ir_phi_fu_109_p6 = 5'd0;
        end else if ((icmp_ln47_reg_206 == 1'd0)) begin
            ap_phi_mux_ir_phi_fu_109_p6 = w_index_reg_201;
        end else begin
            ap_phi_mux_ir_phi_fu_109_p6 = ir_reg_105;
        end
    end else begin
        ap_phi_mux_ir_phi_fu_109_p6 = ir_reg_105;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln47_fu_144_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to2 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln47_reg_206_pp0_iter2_reg == 1'd1))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln47_reg_206_pp0_iter2_reg == 1'd1))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w8_ce0_local = 1'b1;
    end else begin
        w8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_init_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_init_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (layer7_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((icmp_ln47_reg_206_pp0_iter2_reg == 1'd1) & (layer8_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_79 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign icmp_ln47_fu_144_p2 = ((ap_phi_mux_ir_phi_fu_109_p6 == 5'd31) ? 1'b1 : 1'b0);

assign layer8_out_din = $signed(shl_ln_fu_181_p3);

assign sext_ln59_fu_172_p1 = $signed(trunc_ln_reg_220);

assign shl_ln_fu_181_p3 = {{x_fu_175_p2}, {4'd0}};

assign w8_address0 = zext_ln47_fu_133_p1;

assign w_index_fu_138_p2 = (ap_phi_mux_ir_phi_fu_109_p6 + 5'd1);

assign x_fu_175_p2 = ($signed(sext_ln59_fu_172_p1) + $signed(empty_reg_119));

assign zext_ln47_fu_133_p1 = ap_phi_mux_ir_phi_fu_109_p6;

endmodule //myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config8_s
