// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_128u_array_ap_fixed_8_4_5_3_0_128u_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer2_out_dout,
        layer2_out_empty_n,
        layer2_out_read,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer3_out_din,
        layer3_out_full_n,
        layer3_out_write,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [2303:0] layer2_out_dout;
input   layer2_out_empty_n;
output   layer2_out_read;
input  [1:0] layer2_out_num_data_valid;
input  [1:0] layer2_out_fifo_cap;
output  [1023:0] layer3_out_din;
input   layer3_out_full_n;
output   layer3_out_write;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer2_out_read;
reg layer3_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer2_out_blk_n;
reg    layer3_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [7:0] select_ln51_fu_2351_p3;
reg   [7:0] select_ln51_reg_5540;
reg    ap_block_state1;
wire   [7:0] select_ln51_95_fu_2375_p3;
reg   [7:0] select_ln51_95_reg_5545;
wire   [7:0] select_ln51_96_fu_2399_p3;
reg   [7:0] select_ln51_96_reg_5550;
wire   [7:0] select_ln51_97_fu_2423_p3;
reg   [7:0] select_ln51_97_reg_5555;
wire   [7:0] select_ln51_98_fu_2447_p3;
reg   [7:0] select_ln51_98_reg_5560;
wire   [7:0] select_ln51_99_fu_2471_p3;
reg   [7:0] select_ln51_99_reg_5565;
wire   [7:0] select_ln51_100_fu_2495_p3;
reg   [7:0] select_ln51_100_reg_5570;
wire   [7:0] select_ln51_101_fu_2519_p3;
reg   [7:0] select_ln51_101_reg_5575;
wire   [7:0] select_ln51_102_fu_2543_p3;
reg   [7:0] select_ln51_102_reg_5580;
wire   [7:0] select_ln51_103_fu_2567_p3;
reg   [7:0] select_ln51_103_reg_5585;
wire   [7:0] select_ln51_104_fu_2591_p3;
reg   [7:0] select_ln51_104_reg_5590;
wire   [7:0] select_ln51_105_fu_2615_p3;
reg   [7:0] select_ln51_105_reg_5595;
wire   [7:0] select_ln51_106_fu_2639_p3;
reg   [7:0] select_ln51_106_reg_5600;
wire   [7:0] select_ln51_107_fu_2663_p3;
reg   [7:0] select_ln51_107_reg_5605;
wire   [7:0] select_ln51_108_fu_2687_p3;
reg   [7:0] select_ln51_108_reg_5610;
wire   [7:0] select_ln51_109_fu_2711_p3;
reg   [7:0] select_ln51_109_reg_5615;
wire   [7:0] select_ln51_110_fu_2735_p3;
reg   [7:0] select_ln51_110_reg_5620;
wire   [7:0] select_ln51_111_fu_2759_p3;
reg   [7:0] select_ln51_111_reg_5625;
wire   [7:0] select_ln51_112_fu_2783_p3;
reg   [7:0] select_ln51_112_reg_5630;
wire   [7:0] select_ln51_113_fu_2807_p3;
reg   [7:0] select_ln51_113_reg_5635;
wire   [7:0] select_ln51_114_fu_2831_p3;
reg   [7:0] select_ln51_114_reg_5640;
wire   [7:0] select_ln51_115_fu_2855_p3;
reg   [7:0] select_ln51_115_reg_5645;
wire   [7:0] select_ln51_116_fu_2879_p3;
reg   [7:0] select_ln51_116_reg_5650;
wire   [7:0] select_ln51_117_fu_2903_p3;
reg   [7:0] select_ln51_117_reg_5655;
wire   [7:0] select_ln51_118_fu_2927_p3;
reg   [7:0] select_ln51_118_reg_5660;
wire   [7:0] select_ln51_119_fu_2951_p3;
reg   [7:0] select_ln51_119_reg_5665;
wire   [7:0] select_ln51_120_fu_2975_p3;
reg   [7:0] select_ln51_120_reg_5670;
wire   [7:0] select_ln51_121_fu_2999_p3;
reg   [7:0] select_ln51_121_reg_5675;
wire   [7:0] select_ln51_122_fu_3023_p3;
reg   [7:0] select_ln51_122_reg_5680;
wire   [7:0] select_ln51_123_fu_3047_p3;
reg   [7:0] select_ln51_123_reg_5685;
wire   [7:0] select_ln51_124_fu_3071_p3;
reg   [7:0] select_ln51_124_reg_5690;
wire   [7:0] select_ln51_125_fu_3095_p3;
reg   [7:0] select_ln51_125_reg_5695;
wire   [7:0] select_ln51_126_fu_3119_p3;
reg   [7:0] select_ln51_126_reg_5700;
wire   [7:0] select_ln51_127_fu_3143_p3;
reg   [7:0] select_ln51_127_reg_5705;
wire   [7:0] select_ln51_128_fu_3167_p3;
reg   [7:0] select_ln51_128_reg_5710;
wire   [7:0] select_ln51_129_fu_3191_p3;
reg   [7:0] select_ln51_129_reg_5715;
wire   [7:0] select_ln51_130_fu_3215_p3;
reg   [7:0] select_ln51_130_reg_5720;
wire   [7:0] select_ln51_131_fu_3239_p3;
reg   [7:0] select_ln51_131_reg_5725;
wire   [7:0] select_ln51_132_fu_3263_p3;
reg   [7:0] select_ln51_132_reg_5730;
wire   [7:0] select_ln51_133_fu_3287_p3;
reg   [7:0] select_ln51_133_reg_5735;
wire   [7:0] select_ln51_134_fu_3311_p3;
reg   [7:0] select_ln51_134_reg_5740;
wire   [7:0] select_ln51_135_fu_3335_p3;
reg   [7:0] select_ln51_135_reg_5745;
wire   [7:0] select_ln51_136_fu_3359_p3;
reg   [7:0] select_ln51_136_reg_5750;
wire   [7:0] select_ln51_137_fu_3383_p3;
reg   [7:0] select_ln51_137_reg_5755;
wire   [7:0] select_ln51_138_fu_3407_p3;
reg   [7:0] select_ln51_138_reg_5760;
wire   [7:0] select_ln51_139_fu_3431_p3;
reg   [7:0] select_ln51_139_reg_5765;
wire   [7:0] select_ln51_140_fu_3455_p3;
reg   [7:0] select_ln51_140_reg_5770;
wire   [7:0] select_ln51_141_fu_3479_p3;
reg   [7:0] select_ln51_141_reg_5775;
wire   [7:0] select_ln51_142_fu_3503_p3;
reg   [7:0] select_ln51_142_reg_5780;
wire   [7:0] select_ln51_143_fu_3527_p3;
reg   [7:0] select_ln51_143_reg_5785;
wire   [7:0] select_ln51_144_fu_3551_p3;
reg   [7:0] select_ln51_144_reg_5790;
wire   [7:0] select_ln51_145_fu_3575_p3;
reg   [7:0] select_ln51_145_reg_5795;
wire   [7:0] select_ln51_146_fu_3599_p3;
reg   [7:0] select_ln51_146_reg_5800;
wire   [7:0] select_ln51_147_fu_3623_p3;
reg   [7:0] select_ln51_147_reg_5805;
wire   [7:0] select_ln51_148_fu_3647_p3;
reg   [7:0] select_ln51_148_reg_5810;
wire   [7:0] select_ln51_149_fu_3671_p3;
reg   [7:0] select_ln51_149_reg_5815;
wire   [7:0] select_ln51_150_fu_3695_p3;
reg   [7:0] select_ln51_150_reg_5820;
wire   [7:0] select_ln51_151_fu_3719_p3;
reg   [7:0] select_ln51_151_reg_5825;
wire   [7:0] select_ln51_152_fu_3743_p3;
reg   [7:0] select_ln51_152_reg_5830;
wire   [7:0] select_ln51_153_fu_3767_p3;
reg   [7:0] select_ln51_153_reg_5835;
wire   [7:0] select_ln51_154_fu_3791_p3;
reg   [7:0] select_ln51_154_reg_5840;
wire   [7:0] select_ln51_155_fu_3815_p3;
reg   [7:0] select_ln51_155_reg_5845;
wire   [7:0] select_ln51_156_fu_3839_p3;
reg   [7:0] select_ln51_156_reg_5850;
wire   [7:0] select_ln51_157_fu_3863_p3;
reg   [7:0] select_ln51_157_reg_5855;
wire   [7:0] select_ln51_158_fu_3887_p3;
reg   [7:0] select_ln51_158_reg_5860;
wire   [7:0] select_ln51_159_fu_3911_p3;
reg   [7:0] select_ln51_159_reg_5865;
wire   [7:0] select_ln51_160_fu_3935_p3;
reg   [7:0] select_ln51_160_reg_5870;
wire   [7:0] select_ln51_161_fu_3959_p3;
reg   [7:0] select_ln51_161_reg_5875;
wire   [7:0] select_ln51_162_fu_3983_p3;
reg   [7:0] select_ln51_162_reg_5880;
wire   [7:0] select_ln51_163_fu_4007_p3;
reg   [7:0] select_ln51_163_reg_5885;
wire   [7:0] select_ln51_164_fu_4031_p3;
reg   [7:0] select_ln51_164_reg_5890;
wire   [7:0] select_ln51_165_fu_4055_p3;
reg   [7:0] select_ln51_165_reg_5895;
wire   [7:0] select_ln51_166_fu_4079_p3;
reg   [7:0] select_ln51_166_reg_5900;
wire   [7:0] select_ln51_167_fu_4103_p3;
reg   [7:0] select_ln51_167_reg_5905;
wire   [7:0] select_ln51_168_fu_4127_p3;
reg   [7:0] select_ln51_168_reg_5910;
wire   [7:0] select_ln51_169_fu_4151_p3;
reg   [7:0] select_ln51_169_reg_5915;
wire   [7:0] select_ln51_170_fu_4175_p3;
reg   [7:0] select_ln51_170_reg_5920;
wire   [7:0] select_ln51_171_fu_4199_p3;
reg   [7:0] select_ln51_171_reg_5925;
wire   [7:0] select_ln51_172_fu_4223_p3;
reg   [7:0] select_ln51_172_reg_5930;
wire   [7:0] select_ln51_173_fu_4247_p3;
reg   [7:0] select_ln51_173_reg_5935;
wire   [7:0] select_ln51_174_fu_4271_p3;
reg   [7:0] select_ln51_174_reg_5940;
wire   [7:0] select_ln51_175_fu_4295_p3;
reg   [7:0] select_ln51_175_reg_5945;
wire   [7:0] select_ln51_176_fu_4319_p3;
reg   [7:0] select_ln51_176_reg_5950;
wire   [7:0] select_ln51_177_fu_4343_p3;
reg   [7:0] select_ln51_177_reg_5955;
wire   [7:0] select_ln51_178_fu_4367_p3;
reg   [7:0] select_ln51_178_reg_5960;
wire   [7:0] select_ln51_179_fu_4391_p3;
reg   [7:0] select_ln51_179_reg_5965;
wire   [7:0] select_ln51_180_fu_4415_p3;
reg   [7:0] select_ln51_180_reg_5970;
wire   [7:0] select_ln51_181_fu_4439_p3;
reg   [7:0] select_ln51_181_reg_5975;
wire   [7:0] select_ln51_182_fu_4463_p3;
reg   [7:0] select_ln51_182_reg_5980;
wire   [7:0] select_ln51_183_fu_4487_p3;
reg   [7:0] select_ln51_183_reg_5985;
wire   [7:0] select_ln51_184_fu_4511_p3;
reg   [7:0] select_ln51_184_reg_5990;
wire   [7:0] select_ln51_185_fu_4535_p3;
reg   [7:0] select_ln51_185_reg_5995;
wire   [7:0] select_ln51_186_fu_4559_p3;
reg   [7:0] select_ln51_186_reg_6000;
wire   [7:0] select_ln51_187_fu_4583_p3;
reg   [7:0] select_ln51_187_reg_6005;
wire   [7:0] select_ln51_188_fu_4607_p3;
reg   [7:0] select_ln51_188_reg_6010;
wire   [7:0] select_ln51_189_fu_4631_p3;
reg   [7:0] select_ln51_189_reg_6015;
wire   [7:0] select_ln51_190_fu_4655_p3;
reg   [7:0] select_ln51_190_reg_6020;
wire   [7:0] select_ln51_191_fu_4679_p3;
reg   [7:0] select_ln51_191_reg_6025;
wire   [7:0] select_ln51_192_fu_4703_p3;
reg   [7:0] select_ln51_192_reg_6030;
wire   [7:0] select_ln51_193_fu_4727_p3;
reg   [7:0] select_ln51_193_reg_6035;
wire   [7:0] select_ln51_194_fu_4751_p3;
reg   [7:0] select_ln51_194_reg_6040;
wire   [7:0] select_ln51_195_fu_4775_p3;
reg   [7:0] select_ln51_195_reg_6045;
wire   [7:0] select_ln51_196_fu_4799_p3;
reg   [7:0] select_ln51_196_reg_6050;
wire   [7:0] select_ln51_197_fu_4823_p3;
reg   [7:0] select_ln51_197_reg_6055;
wire   [7:0] select_ln51_198_fu_4847_p3;
reg   [7:0] select_ln51_198_reg_6060;
wire   [7:0] select_ln51_199_fu_4871_p3;
reg   [7:0] select_ln51_199_reg_6065;
wire   [7:0] select_ln51_200_fu_4895_p3;
reg   [7:0] select_ln51_200_reg_6070;
wire   [7:0] select_ln51_201_fu_4919_p3;
reg   [7:0] select_ln51_201_reg_6075;
wire   [7:0] select_ln51_202_fu_4943_p3;
reg   [7:0] select_ln51_202_reg_6080;
wire   [7:0] select_ln51_203_fu_4967_p3;
reg   [7:0] select_ln51_203_reg_6085;
wire   [7:0] select_ln51_204_fu_4991_p3;
reg   [7:0] select_ln51_204_reg_6090;
wire   [7:0] select_ln51_205_fu_5015_p3;
reg   [7:0] select_ln51_205_reg_6095;
wire   [7:0] select_ln51_206_fu_5039_p3;
reg   [7:0] select_ln51_206_reg_6100;
wire   [7:0] select_ln51_207_fu_5063_p3;
reg   [7:0] select_ln51_207_reg_6105;
wire   [7:0] select_ln51_208_fu_5087_p3;
reg   [7:0] select_ln51_208_reg_6110;
wire   [7:0] select_ln51_209_fu_5111_p3;
reg   [7:0] select_ln51_209_reg_6115;
wire   [7:0] select_ln51_210_fu_5135_p3;
reg   [7:0] select_ln51_210_reg_6120;
wire   [7:0] select_ln51_211_fu_5159_p3;
reg   [7:0] select_ln51_211_reg_6125;
wire   [7:0] select_ln51_212_fu_5183_p3;
reg   [7:0] select_ln51_212_reg_6130;
wire   [7:0] select_ln51_213_fu_5207_p3;
reg   [7:0] select_ln51_213_reg_6135;
wire   [7:0] select_ln51_214_fu_5231_p3;
reg   [7:0] select_ln51_214_reg_6140;
wire   [7:0] select_ln51_215_fu_5255_p3;
reg   [7:0] select_ln51_215_reg_6145;
wire   [7:0] select_ln51_216_fu_5279_p3;
reg   [7:0] select_ln51_216_reg_6150;
wire   [7:0] select_ln51_217_fu_5303_p3;
reg   [7:0] select_ln51_217_reg_6155;
wire   [7:0] select_ln51_218_fu_5327_p3;
reg   [7:0] select_ln51_218_reg_6160;
wire   [7:0] select_ln51_219_fu_5351_p3;
reg   [7:0] select_ln51_219_reg_6165;
wire   [7:0] select_ln51_220_fu_5375_p3;
reg   [7:0] select_ln51_220_reg_6170;
wire   [7:0] select_ln51_221_fu_5399_p3;
reg   [7:0] select_ln51_221_reg_6175;
wire   [17:0] trunc_ln44_fu_1061_p1;
wire   [0:0] icmp_ln51_fu_2335_p2;
wire   [7:0] trunc_ln4_fu_2341_p4;
wire   [17:0] trunc_ln44_s_fu_1065_p4;
wire   [0:0] icmp_ln51_95_fu_2359_p2;
wire   [7:0] trunc_ln52_s_fu_2365_p4;
wire   [17:0] trunc_ln44_93_fu_1075_p4;
wire   [0:0] icmp_ln51_96_fu_2383_p2;
wire   [7:0] trunc_ln52_93_fu_2389_p4;
wire   [17:0] trunc_ln44_94_fu_1085_p4;
wire   [0:0] icmp_ln51_97_fu_2407_p2;
wire   [7:0] trunc_ln52_94_fu_2413_p4;
wire   [17:0] trunc_ln44_95_fu_1095_p4;
wire   [0:0] icmp_ln51_98_fu_2431_p2;
wire   [7:0] trunc_ln52_95_fu_2437_p4;
wire   [17:0] trunc_ln44_96_fu_1105_p4;
wire   [0:0] icmp_ln51_99_fu_2455_p2;
wire   [7:0] trunc_ln52_96_fu_2461_p4;
wire   [17:0] trunc_ln44_97_fu_1115_p4;
wire   [0:0] icmp_ln51_100_fu_2479_p2;
wire   [7:0] trunc_ln52_97_fu_2485_p4;
wire   [17:0] trunc_ln44_98_fu_1125_p4;
wire   [0:0] icmp_ln51_101_fu_2503_p2;
wire   [7:0] trunc_ln52_98_fu_2509_p4;
wire   [17:0] trunc_ln44_99_fu_1135_p4;
wire   [0:0] icmp_ln51_102_fu_2527_p2;
wire   [7:0] trunc_ln52_99_fu_2533_p4;
wire   [17:0] trunc_ln44_100_fu_1145_p4;
wire   [0:0] icmp_ln51_103_fu_2551_p2;
wire   [7:0] trunc_ln52_100_fu_2557_p4;
wire   [17:0] trunc_ln44_101_fu_1155_p4;
wire   [0:0] icmp_ln51_104_fu_2575_p2;
wire   [7:0] trunc_ln52_101_fu_2581_p4;
wire   [17:0] trunc_ln44_102_fu_1165_p4;
wire   [0:0] icmp_ln51_105_fu_2599_p2;
wire   [7:0] trunc_ln52_102_fu_2605_p4;
wire   [17:0] trunc_ln44_103_fu_1175_p4;
wire   [0:0] icmp_ln51_106_fu_2623_p2;
wire   [7:0] trunc_ln52_103_fu_2629_p4;
wire   [17:0] trunc_ln44_104_fu_1185_p4;
wire   [0:0] icmp_ln51_107_fu_2647_p2;
wire   [7:0] trunc_ln52_104_fu_2653_p4;
wire   [17:0] trunc_ln44_105_fu_1195_p4;
wire   [0:0] icmp_ln51_108_fu_2671_p2;
wire   [7:0] trunc_ln52_105_fu_2677_p4;
wire   [17:0] trunc_ln44_106_fu_1205_p4;
wire   [0:0] icmp_ln51_109_fu_2695_p2;
wire   [7:0] trunc_ln52_106_fu_2701_p4;
wire   [17:0] trunc_ln44_107_fu_1215_p4;
wire   [0:0] icmp_ln51_110_fu_2719_p2;
wire   [7:0] trunc_ln52_107_fu_2725_p4;
wire   [17:0] trunc_ln44_108_fu_1225_p4;
wire   [0:0] icmp_ln51_111_fu_2743_p2;
wire   [7:0] trunc_ln52_108_fu_2749_p4;
wire   [17:0] trunc_ln44_109_fu_1235_p4;
wire   [0:0] icmp_ln51_112_fu_2767_p2;
wire   [7:0] trunc_ln52_109_fu_2773_p4;
wire   [17:0] trunc_ln44_110_fu_1245_p4;
wire   [0:0] icmp_ln51_113_fu_2791_p2;
wire   [7:0] trunc_ln52_110_fu_2797_p4;
wire   [17:0] trunc_ln44_111_fu_1255_p4;
wire   [0:0] icmp_ln51_114_fu_2815_p2;
wire   [7:0] trunc_ln52_111_fu_2821_p4;
wire   [17:0] trunc_ln44_112_fu_1265_p4;
wire   [0:0] icmp_ln51_115_fu_2839_p2;
wire   [7:0] trunc_ln52_112_fu_2845_p4;
wire   [17:0] trunc_ln44_113_fu_1275_p4;
wire   [0:0] icmp_ln51_116_fu_2863_p2;
wire   [7:0] trunc_ln52_113_fu_2869_p4;
wire   [17:0] trunc_ln44_114_fu_1285_p4;
wire   [0:0] icmp_ln51_117_fu_2887_p2;
wire   [7:0] trunc_ln52_114_fu_2893_p4;
wire   [17:0] trunc_ln44_115_fu_1295_p4;
wire   [0:0] icmp_ln51_118_fu_2911_p2;
wire   [7:0] trunc_ln52_115_fu_2917_p4;
wire   [17:0] trunc_ln44_116_fu_1305_p4;
wire   [0:0] icmp_ln51_119_fu_2935_p2;
wire   [7:0] trunc_ln52_116_fu_2941_p4;
wire   [17:0] trunc_ln44_117_fu_1315_p4;
wire   [0:0] icmp_ln51_120_fu_2959_p2;
wire   [7:0] trunc_ln52_117_fu_2965_p4;
wire   [17:0] trunc_ln44_118_fu_1325_p4;
wire   [0:0] icmp_ln51_121_fu_2983_p2;
wire   [7:0] trunc_ln52_118_fu_2989_p4;
wire   [17:0] trunc_ln44_119_fu_1335_p4;
wire   [0:0] icmp_ln51_122_fu_3007_p2;
wire   [7:0] trunc_ln52_119_fu_3013_p4;
wire   [17:0] trunc_ln44_120_fu_1345_p4;
wire   [0:0] icmp_ln51_123_fu_3031_p2;
wire   [7:0] trunc_ln52_120_fu_3037_p4;
wire   [17:0] trunc_ln44_121_fu_1355_p4;
wire   [0:0] icmp_ln51_124_fu_3055_p2;
wire   [7:0] trunc_ln52_121_fu_3061_p4;
wire   [17:0] trunc_ln44_122_fu_1365_p4;
wire   [0:0] icmp_ln51_125_fu_3079_p2;
wire   [7:0] trunc_ln52_122_fu_3085_p4;
wire   [17:0] trunc_ln44_123_fu_1375_p4;
wire   [0:0] icmp_ln51_126_fu_3103_p2;
wire   [7:0] trunc_ln52_123_fu_3109_p4;
wire   [17:0] trunc_ln44_124_fu_1385_p4;
wire   [0:0] icmp_ln51_127_fu_3127_p2;
wire   [7:0] trunc_ln52_124_fu_3133_p4;
wire   [17:0] trunc_ln44_125_fu_1395_p4;
wire   [0:0] icmp_ln51_128_fu_3151_p2;
wire   [7:0] trunc_ln52_125_fu_3157_p4;
wire   [17:0] trunc_ln44_126_fu_1405_p4;
wire   [0:0] icmp_ln51_129_fu_3175_p2;
wire   [7:0] trunc_ln52_126_fu_3181_p4;
wire   [17:0] trunc_ln44_127_fu_1415_p4;
wire   [0:0] icmp_ln51_130_fu_3199_p2;
wire   [7:0] trunc_ln52_127_fu_3205_p4;
wire   [17:0] trunc_ln44_128_fu_1425_p4;
wire   [0:0] icmp_ln51_131_fu_3223_p2;
wire   [7:0] trunc_ln52_128_fu_3229_p4;
wire   [17:0] trunc_ln44_129_fu_1435_p4;
wire   [0:0] icmp_ln51_132_fu_3247_p2;
wire   [7:0] trunc_ln52_129_fu_3253_p4;
wire   [17:0] trunc_ln44_130_fu_1445_p4;
wire   [0:0] icmp_ln51_133_fu_3271_p2;
wire   [7:0] trunc_ln52_130_fu_3277_p4;
wire   [17:0] trunc_ln44_131_fu_1455_p4;
wire   [0:0] icmp_ln51_134_fu_3295_p2;
wire   [7:0] trunc_ln52_131_fu_3301_p4;
wire   [17:0] trunc_ln44_132_fu_1465_p4;
wire   [0:0] icmp_ln51_135_fu_3319_p2;
wire   [7:0] trunc_ln52_132_fu_3325_p4;
wire   [17:0] trunc_ln44_133_fu_1475_p4;
wire   [0:0] icmp_ln51_136_fu_3343_p2;
wire   [7:0] trunc_ln52_133_fu_3349_p4;
wire   [17:0] trunc_ln44_134_fu_1485_p4;
wire   [0:0] icmp_ln51_137_fu_3367_p2;
wire   [7:0] trunc_ln52_134_fu_3373_p4;
wire   [17:0] trunc_ln44_135_fu_1495_p4;
wire   [0:0] icmp_ln51_138_fu_3391_p2;
wire   [7:0] trunc_ln52_135_fu_3397_p4;
wire   [17:0] trunc_ln44_136_fu_1505_p4;
wire   [0:0] icmp_ln51_139_fu_3415_p2;
wire   [7:0] trunc_ln52_136_fu_3421_p4;
wire   [17:0] trunc_ln44_137_fu_1515_p4;
wire   [0:0] icmp_ln51_140_fu_3439_p2;
wire   [7:0] trunc_ln52_137_fu_3445_p4;
wire   [17:0] trunc_ln44_138_fu_1525_p4;
wire   [0:0] icmp_ln51_141_fu_3463_p2;
wire   [7:0] trunc_ln52_138_fu_3469_p4;
wire   [17:0] trunc_ln44_139_fu_1535_p4;
wire   [0:0] icmp_ln51_142_fu_3487_p2;
wire   [7:0] trunc_ln52_139_fu_3493_p4;
wire   [17:0] trunc_ln44_140_fu_1545_p4;
wire   [0:0] icmp_ln51_143_fu_3511_p2;
wire   [7:0] trunc_ln52_140_fu_3517_p4;
wire   [17:0] trunc_ln44_141_fu_1555_p4;
wire   [0:0] icmp_ln51_144_fu_3535_p2;
wire   [7:0] trunc_ln52_141_fu_3541_p4;
wire   [17:0] trunc_ln44_142_fu_1565_p4;
wire   [0:0] icmp_ln51_145_fu_3559_p2;
wire   [7:0] trunc_ln52_142_fu_3565_p4;
wire   [17:0] trunc_ln44_143_fu_1575_p4;
wire   [0:0] icmp_ln51_146_fu_3583_p2;
wire   [7:0] trunc_ln52_143_fu_3589_p4;
wire   [17:0] trunc_ln44_144_fu_1585_p4;
wire   [0:0] icmp_ln51_147_fu_3607_p2;
wire   [7:0] trunc_ln52_144_fu_3613_p4;
wire   [17:0] trunc_ln44_145_fu_1595_p4;
wire   [0:0] icmp_ln51_148_fu_3631_p2;
wire   [7:0] trunc_ln52_145_fu_3637_p4;
wire   [17:0] trunc_ln44_146_fu_1605_p4;
wire   [0:0] icmp_ln51_149_fu_3655_p2;
wire   [7:0] trunc_ln52_146_fu_3661_p4;
wire   [17:0] trunc_ln44_147_fu_1615_p4;
wire   [0:0] icmp_ln51_150_fu_3679_p2;
wire   [7:0] trunc_ln52_147_fu_3685_p4;
wire   [17:0] trunc_ln44_148_fu_1625_p4;
wire   [0:0] icmp_ln51_151_fu_3703_p2;
wire   [7:0] trunc_ln52_148_fu_3709_p4;
wire   [17:0] trunc_ln44_149_fu_1635_p4;
wire   [0:0] icmp_ln51_152_fu_3727_p2;
wire   [7:0] trunc_ln52_149_fu_3733_p4;
wire   [17:0] trunc_ln44_150_fu_1645_p4;
wire   [0:0] icmp_ln51_153_fu_3751_p2;
wire   [7:0] trunc_ln52_150_fu_3757_p4;
wire   [17:0] trunc_ln44_151_fu_1655_p4;
wire   [0:0] icmp_ln51_154_fu_3775_p2;
wire   [7:0] trunc_ln52_151_fu_3781_p4;
wire   [17:0] trunc_ln44_152_fu_1665_p4;
wire   [0:0] icmp_ln51_155_fu_3799_p2;
wire   [7:0] trunc_ln52_152_fu_3805_p4;
wire   [17:0] trunc_ln44_153_fu_1675_p4;
wire   [0:0] icmp_ln51_156_fu_3823_p2;
wire   [7:0] trunc_ln52_153_fu_3829_p4;
wire   [17:0] trunc_ln44_154_fu_1685_p4;
wire   [0:0] icmp_ln51_157_fu_3847_p2;
wire   [7:0] trunc_ln52_154_fu_3853_p4;
wire   [17:0] trunc_ln44_155_fu_1695_p4;
wire   [0:0] icmp_ln51_158_fu_3871_p2;
wire   [7:0] trunc_ln52_155_fu_3877_p4;
wire   [17:0] trunc_ln44_156_fu_1705_p4;
wire   [0:0] icmp_ln51_159_fu_3895_p2;
wire   [7:0] trunc_ln52_156_fu_3901_p4;
wire   [17:0] trunc_ln44_157_fu_1715_p4;
wire   [0:0] icmp_ln51_160_fu_3919_p2;
wire   [7:0] trunc_ln52_157_fu_3925_p4;
wire   [17:0] trunc_ln44_158_fu_1725_p4;
wire   [0:0] icmp_ln51_161_fu_3943_p2;
wire   [7:0] trunc_ln52_158_fu_3949_p4;
wire   [17:0] trunc_ln44_159_fu_1735_p4;
wire   [0:0] icmp_ln51_162_fu_3967_p2;
wire   [7:0] trunc_ln52_159_fu_3973_p4;
wire   [17:0] trunc_ln44_160_fu_1745_p4;
wire   [0:0] icmp_ln51_163_fu_3991_p2;
wire   [7:0] trunc_ln52_160_fu_3997_p4;
wire   [17:0] trunc_ln44_161_fu_1755_p4;
wire   [0:0] icmp_ln51_164_fu_4015_p2;
wire   [7:0] trunc_ln52_161_fu_4021_p4;
wire   [17:0] trunc_ln44_162_fu_1765_p4;
wire   [0:0] icmp_ln51_165_fu_4039_p2;
wire   [7:0] trunc_ln52_162_fu_4045_p4;
wire   [17:0] trunc_ln44_163_fu_1775_p4;
wire   [0:0] icmp_ln51_166_fu_4063_p2;
wire   [7:0] trunc_ln52_163_fu_4069_p4;
wire   [17:0] trunc_ln44_164_fu_1785_p4;
wire   [0:0] icmp_ln51_167_fu_4087_p2;
wire   [7:0] trunc_ln52_164_fu_4093_p4;
wire   [17:0] trunc_ln44_165_fu_1795_p4;
wire   [0:0] icmp_ln51_168_fu_4111_p2;
wire   [7:0] trunc_ln52_165_fu_4117_p4;
wire   [17:0] trunc_ln44_166_fu_1805_p4;
wire   [0:0] icmp_ln51_169_fu_4135_p2;
wire   [7:0] trunc_ln52_166_fu_4141_p4;
wire   [17:0] trunc_ln44_167_fu_1815_p4;
wire   [0:0] icmp_ln51_170_fu_4159_p2;
wire   [7:0] trunc_ln52_167_fu_4165_p4;
wire   [17:0] trunc_ln44_168_fu_1825_p4;
wire   [0:0] icmp_ln51_171_fu_4183_p2;
wire   [7:0] trunc_ln52_168_fu_4189_p4;
wire   [17:0] trunc_ln44_169_fu_1835_p4;
wire   [0:0] icmp_ln51_172_fu_4207_p2;
wire   [7:0] trunc_ln52_169_fu_4213_p4;
wire   [17:0] trunc_ln44_170_fu_1845_p4;
wire   [0:0] icmp_ln51_173_fu_4231_p2;
wire   [7:0] trunc_ln52_170_fu_4237_p4;
wire   [17:0] trunc_ln44_171_fu_1855_p4;
wire   [0:0] icmp_ln51_174_fu_4255_p2;
wire   [7:0] trunc_ln52_171_fu_4261_p4;
wire   [17:0] trunc_ln44_172_fu_1865_p4;
wire   [0:0] icmp_ln51_175_fu_4279_p2;
wire   [7:0] trunc_ln52_172_fu_4285_p4;
wire   [17:0] trunc_ln44_173_fu_1875_p4;
wire   [0:0] icmp_ln51_176_fu_4303_p2;
wire   [7:0] trunc_ln52_173_fu_4309_p4;
wire   [17:0] trunc_ln44_174_fu_1885_p4;
wire   [0:0] icmp_ln51_177_fu_4327_p2;
wire   [7:0] trunc_ln52_174_fu_4333_p4;
wire   [17:0] trunc_ln44_175_fu_1895_p4;
wire   [0:0] icmp_ln51_178_fu_4351_p2;
wire   [7:0] trunc_ln52_175_fu_4357_p4;
wire   [17:0] trunc_ln44_176_fu_1905_p4;
wire   [0:0] icmp_ln51_179_fu_4375_p2;
wire   [7:0] trunc_ln52_176_fu_4381_p4;
wire   [17:0] trunc_ln44_177_fu_1915_p4;
wire   [0:0] icmp_ln51_180_fu_4399_p2;
wire   [7:0] trunc_ln52_177_fu_4405_p4;
wire   [17:0] trunc_ln44_178_fu_1925_p4;
wire   [0:0] icmp_ln51_181_fu_4423_p2;
wire   [7:0] trunc_ln52_178_fu_4429_p4;
wire   [17:0] trunc_ln44_179_fu_1935_p4;
wire   [0:0] icmp_ln51_182_fu_4447_p2;
wire   [7:0] trunc_ln52_179_fu_4453_p4;
wire   [17:0] trunc_ln44_180_fu_1945_p4;
wire   [0:0] icmp_ln51_183_fu_4471_p2;
wire   [7:0] trunc_ln52_180_fu_4477_p4;
wire   [17:0] trunc_ln44_181_fu_1955_p4;
wire   [0:0] icmp_ln51_184_fu_4495_p2;
wire   [7:0] trunc_ln52_181_fu_4501_p4;
wire   [17:0] trunc_ln44_182_fu_1965_p4;
wire   [0:0] icmp_ln51_185_fu_4519_p2;
wire   [7:0] trunc_ln52_182_fu_4525_p4;
wire   [17:0] trunc_ln44_183_fu_1975_p4;
wire   [0:0] icmp_ln51_186_fu_4543_p2;
wire   [7:0] trunc_ln52_183_fu_4549_p4;
wire   [17:0] trunc_ln44_184_fu_1985_p4;
wire   [0:0] icmp_ln51_187_fu_4567_p2;
wire   [7:0] trunc_ln52_184_fu_4573_p4;
wire   [17:0] trunc_ln44_185_fu_1995_p4;
wire   [0:0] icmp_ln51_188_fu_4591_p2;
wire   [7:0] trunc_ln52_185_fu_4597_p4;
wire   [17:0] trunc_ln44_186_fu_2005_p4;
wire   [0:0] icmp_ln51_189_fu_4615_p2;
wire   [7:0] trunc_ln52_186_fu_4621_p4;
wire   [17:0] trunc_ln44_187_fu_2015_p4;
wire   [0:0] icmp_ln51_190_fu_4639_p2;
wire   [7:0] trunc_ln52_187_fu_4645_p4;
wire   [17:0] trunc_ln44_188_fu_2025_p4;
wire   [0:0] icmp_ln51_191_fu_4663_p2;
wire   [7:0] trunc_ln52_188_fu_4669_p4;
wire   [17:0] trunc_ln44_189_fu_2035_p4;
wire   [0:0] icmp_ln51_192_fu_4687_p2;
wire   [7:0] trunc_ln52_189_fu_4693_p4;
wire   [17:0] trunc_ln44_190_fu_2045_p4;
wire   [0:0] icmp_ln51_193_fu_4711_p2;
wire   [7:0] trunc_ln52_190_fu_4717_p4;
wire   [17:0] trunc_ln44_191_fu_2055_p4;
wire   [0:0] icmp_ln51_194_fu_4735_p2;
wire   [7:0] trunc_ln52_191_fu_4741_p4;
wire   [17:0] trunc_ln44_192_fu_2065_p4;
wire   [0:0] icmp_ln51_195_fu_4759_p2;
wire   [7:0] trunc_ln52_192_fu_4765_p4;
wire   [17:0] trunc_ln44_193_fu_2075_p4;
wire   [0:0] icmp_ln51_196_fu_4783_p2;
wire   [7:0] trunc_ln52_193_fu_4789_p4;
wire   [17:0] trunc_ln44_194_fu_2085_p4;
wire   [0:0] icmp_ln51_197_fu_4807_p2;
wire   [7:0] trunc_ln52_194_fu_4813_p4;
wire   [17:0] trunc_ln44_195_fu_2095_p4;
wire   [0:0] icmp_ln51_198_fu_4831_p2;
wire   [7:0] trunc_ln52_195_fu_4837_p4;
wire   [17:0] trunc_ln44_196_fu_2105_p4;
wire   [0:0] icmp_ln51_199_fu_4855_p2;
wire   [7:0] trunc_ln52_196_fu_4861_p4;
wire   [17:0] trunc_ln44_197_fu_2115_p4;
wire   [0:0] icmp_ln51_200_fu_4879_p2;
wire   [7:0] trunc_ln52_197_fu_4885_p4;
wire   [17:0] trunc_ln44_198_fu_2125_p4;
wire   [0:0] icmp_ln51_201_fu_4903_p2;
wire   [7:0] trunc_ln52_198_fu_4909_p4;
wire   [17:0] trunc_ln44_199_fu_2135_p4;
wire   [0:0] icmp_ln51_202_fu_4927_p2;
wire   [7:0] trunc_ln52_199_fu_4933_p4;
wire   [17:0] trunc_ln44_200_fu_2145_p4;
wire   [0:0] icmp_ln51_203_fu_4951_p2;
wire   [7:0] trunc_ln52_200_fu_4957_p4;
wire   [17:0] trunc_ln44_201_fu_2155_p4;
wire   [0:0] icmp_ln51_204_fu_4975_p2;
wire   [7:0] trunc_ln52_201_fu_4981_p4;
wire   [17:0] trunc_ln44_202_fu_2165_p4;
wire   [0:0] icmp_ln51_205_fu_4999_p2;
wire   [7:0] trunc_ln52_202_fu_5005_p4;
wire   [17:0] trunc_ln44_203_fu_2175_p4;
wire   [0:0] icmp_ln51_206_fu_5023_p2;
wire   [7:0] trunc_ln52_203_fu_5029_p4;
wire   [17:0] trunc_ln44_204_fu_2185_p4;
wire   [0:0] icmp_ln51_207_fu_5047_p2;
wire   [7:0] trunc_ln52_204_fu_5053_p4;
wire   [17:0] trunc_ln44_205_fu_2195_p4;
wire   [0:0] icmp_ln51_208_fu_5071_p2;
wire   [7:0] trunc_ln52_205_fu_5077_p4;
wire   [17:0] trunc_ln44_206_fu_2205_p4;
wire   [0:0] icmp_ln51_209_fu_5095_p2;
wire   [7:0] trunc_ln52_206_fu_5101_p4;
wire   [17:0] trunc_ln44_207_fu_2215_p4;
wire   [0:0] icmp_ln51_210_fu_5119_p2;
wire   [7:0] trunc_ln52_207_fu_5125_p4;
wire   [17:0] trunc_ln44_208_fu_2225_p4;
wire   [0:0] icmp_ln51_211_fu_5143_p2;
wire   [7:0] trunc_ln52_208_fu_5149_p4;
wire   [17:0] trunc_ln44_209_fu_2235_p4;
wire   [0:0] icmp_ln51_212_fu_5167_p2;
wire   [7:0] trunc_ln52_209_fu_5173_p4;
wire   [17:0] trunc_ln44_210_fu_2245_p4;
wire   [0:0] icmp_ln51_213_fu_5191_p2;
wire   [7:0] trunc_ln52_210_fu_5197_p4;
wire   [17:0] trunc_ln44_211_fu_2255_p4;
wire   [0:0] icmp_ln51_214_fu_5215_p2;
wire   [7:0] trunc_ln52_211_fu_5221_p4;
wire   [17:0] trunc_ln44_212_fu_2265_p4;
wire   [0:0] icmp_ln51_215_fu_5239_p2;
wire   [7:0] trunc_ln52_212_fu_5245_p4;
wire   [17:0] trunc_ln44_213_fu_2275_p4;
wire   [0:0] icmp_ln51_216_fu_5263_p2;
wire   [7:0] trunc_ln52_213_fu_5269_p4;
wire   [17:0] trunc_ln44_214_fu_2285_p4;
wire   [0:0] icmp_ln51_217_fu_5287_p2;
wire   [7:0] trunc_ln52_214_fu_5293_p4;
wire   [17:0] trunc_ln44_215_fu_2295_p4;
wire   [0:0] icmp_ln51_218_fu_5311_p2;
wire   [7:0] trunc_ln52_215_fu_5317_p4;
wire   [17:0] trunc_ln44_216_fu_2305_p4;
wire   [0:0] icmp_ln51_219_fu_5335_p2;
wire   [7:0] trunc_ln52_216_fu_5341_p4;
wire   [17:0] trunc_ln44_217_fu_2315_p4;
wire   [0:0] icmp_ln51_220_fu_5359_p2;
wire   [7:0] trunc_ln52_217_fu_5365_p4;
wire   [17:0] trunc_ln44_218_fu_2325_p4;
wire   [0:0] icmp_ln51_221_fu_5383_p2;
wire   [7:0] trunc_ln52_218_fu_5389_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_100_reg_5570 <= select_ln51_100_fu_2495_p3;
        select_ln51_101_reg_5575 <= select_ln51_101_fu_2519_p3;
        select_ln51_102_reg_5580 <= select_ln51_102_fu_2543_p3;
        select_ln51_103_reg_5585 <= select_ln51_103_fu_2567_p3;
        select_ln51_104_reg_5590 <= select_ln51_104_fu_2591_p3;
        select_ln51_105_reg_5595 <= select_ln51_105_fu_2615_p3;
        select_ln51_106_reg_5600 <= select_ln51_106_fu_2639_p3;
        select_ln51_107_reg_5605 <= select_ln51_107_fu_2663_p3;
        select_ln51_108_reg_5610 <= select_ln51_108_fu_2687_p3;
        select_ln51_109_reg_5615 <= select_ln51_109_fu_2711_p3;
        select_ln51_110_reg_5620 <= select_ln51_110_fu_2735_p3;
        select_ln51_111_reg_5625 <= select_ln51_111_fu_2759_p3;
        select_ln51_112_reg_5630 <= select_ln51_112_fu_2783_p3;
        select_ln51_113_reg_5635 <= select_ln51_113_fu_2807_p3;
        select_ln51_114_reg_5640 <= select_ln51_114_fu_2831_p3;
        select_ln51_115_reg_5645 <= select_ln51_115_fu_2855_p3;
        select_ln51_116_reg_5650 <= select_ln51_116_fu_2879_p3;
        select_ln51_117_reg_5655 <= select_ln51_117_fu_2903_p3;
        select_ln51_118_reg_5660 <= select_ln51_118_fu_2927_p3;
        select_ln51_119_reg_5665 <= select_ln51_119_fu_2951_p3;
        select_ln51_120_reg_5670 <= select_ln51_120_fu_2975_p3;
        select_ln51_121_reg_5675 <= select_ln51_121_fu_2999_p3;
        select_ln51_122_reg_5680 <= select_ln51_122_fu_3023_p3;
        select_ln51_123_reg_5685 <= select_ln51_123_fu_3047_p3;
        select_ln51_124_reg_5690 <= select_ln51_124_fu_3071_p3;
        select_ln51_125_reg_5695 <= select_ln51_125_fu_3095_p3;
        select_ln51_126_reg_5700 <= select_ln51_126_fu_3119_p3;
        select_ln51_127_reg_5705 <= select_ln51_127_fu_3143_p3;
        select_ln51_128_reg_5710 <= select_ln51_128_fu_3167_p3;
        select_ln51_129_reg_5715 <= select_ln51_129_fu_3191_p3;
        select_ln51_130_reg_5720 <= select_ln51_130_fu_3215_p3;
        select_ln51_131_reg_5725 <= select_ln51_131_fu_3239_p3;
        select_ln51_132_reg_5730 <= select_ln51_132_fu_3263_p3;
        select_ln51_133_reg_5735 <= select_ln51_133_fu_3287_p3;
        select_ln51_134_reg_5740 <= select_ln51_134_fu_3311_p3;
        select_ln51_135_reg_5745 <= select_ln51_135_fu_3335_p3;
        select_ln51_136_reg_5750 <= select_ln51_136_fu_3359_p3;
        select_ln51_137_reg_5755 <= select_ln51_137_fu_3383_p3;
        select_ln51_138_reg_5760 <= select_ln51_138_fu_3407_p3;
        select_ln51_139_reg_5765 <= select_ln51_139_fu_3431_p3;
        select_ln51_140_reg_5770 <= select_ln51_140_fu_3455_p3;
        select_ln51_141_reg_5775 <= select_ln51_141_fu_3479_p3;
        select_ln51_142_reg_5780 <= select_ln51_142_fu_3503_p3;
        select_ln51_143_reg_5785 <= select_ln51_143_fu_3527_p3;
        select_ln51_144_reg_5790 <= select_ln51_144_fu_3551_p3;
        select_ln51_145_reg_5795 <= select_ln51_145_fu_3575_p3;
        select_ln51_146_reg_5800 <= select_ln51_146_fu_3599_p3;
        select_ln51_147_reg_5805 <= select_ln51_147_fu_3623_p3;
        select_ln51_148_reg_5810 <= select_ln51_148_fu_3647_p3;
        select_ln51_149_reg_5815 <= select_ln51_149_fu_3671_p3;
        select_ln51_150_reg_5820 <= select_ln51_150_fu_3695_p3;
        select_ln51_151_reg_5825 <= select_ln51_151_fu_3719_p3;
        select_ln51_152_reg_5830 <= select_ln51_152_fu_3743_p3;
        select_ln51_153_reg_5835 <= select_ln51_153_fu_3767_p3;
        select_ln51_154_reg_5840 <= select_ln51_154_fu_3791_p3;
        select_ln51_155_reg_5845 <= select_ln51_155_fu_3815_p3;
        select_ln51_156_reg_5850 <= select_ln51_156_fu_3839_p3;
        select_ln51_157_reg_5855 <= select_ln51_157_fu_3863_p3;
        select_ln51_158_reg_5860 <= select_ln51_158_fu_3887_p3;
        select_ln51_159_reg_5865 <= select_ln51_159_fu_3911_p3;
        select_ln51_160_reg_5870 <= select_ln51_160_fu_3935_p3;
        select_ln51_161_reg_5875 <= select_ln51_161_fu_3959_p3;
        select_ln51_162_reg_5880 <= select_ln51_162_fu_3983_p3;
        select_ln51_163_reg_5885 <= select_ln51_163_fu_4007_p3;
        select_ln51_164_reg_5890 <= select_ln51_164_fu_4031_p3;
        select_ln51_165_reg_5895 <= select_ln51_165_fu_4055_p3;
        select_ln51_166_reg_5900 <= select_ln51_166_fu_4079_p3;
        select_ln51_167_reg_5905 <= select_ln51_167_fu_4103_p3;
        select_ln51_168_reg_5910 <= select_ln51_168_fu_4127_p3;
        select_ln51_169_reg_5915 <= select_ln51_169_fu_4151_p3;
        select_ln51_170_reg_5920 <= select_ln51_170_fu_4175_p3;
        select_ln51_171_reg_5925 <= select_ln51_171_fu_4199_p3;
        select_ln51_172_reg_5930 <= select_ln51_172_fu_4223_p3;
        select_ln51_173_reg_5935 <= select_ln51_173_fu_4247_p3;
        select_ln51_174_reg_5940 <= select_ln51_174_fu_4271_p3;
        select_ln51_175_reg_5945 <= select_ln51_175_fu_4295_p3;
        select_ln51_176_reg_5950 <= select_ln51_176_fu_4319_p3;
        select_ln51_177_reg_5955 <= select_ln51_177_fu_4343_p3;
        select_ln51_178_reg_5960 <= select_ln51_178_fu_4367_p3;
        select_ln51_179_reg_5965 <= select_ln51_179_fu_4391_p3;
        select_ln51_180_reg_5970 <= select_ln51_180_fu_4415_p3;
        select_ln51_181_reg_5975 <= select_ln51_181_fu_4439_p3;
        select_ln51_182_reg_5980 <= select_ln51_182_fu_4463_p3;
        select_ln51_183_reg_5985 <= select_ln51_183_fu_4487_p3;
        select_ln51_184_reg_5990 <= select_ln51_184_fu_4511_p3;
        select_ln51_185_reg_5995 <= select_ln51_185_fu_4535_p3;
        select_ln51_186_reg_6000 <= select_ln51_186_fu_4559_p3;
        select_ln51_187_reg_6005 <= select_ln51_187_fu_4583_p3;
        select_ln51_188_reg_6010 <= select_ln51_188_fu_4607_p3;
        select_ln51_189_reg_6015 <= select_ln51_189_fu_4631_p3;
        select_ln51_190_reg_6020 <= select_ln51_190_fu_4655_p3;
        select_ln51_191_reg_6025 <= select_ln51_191_fu_4679_p3;
        select_ln51_192_reg_6030 <= select_ln51_192_fu_4703_p3;
        select_ln51_193_reg_6035 <= select_ln51_193_fu_4727_p3;
        select_ln51_194_reg_6040 <= select_ln51_194_fu_4751_p3;
        select_ln51_195_reg_6045 <= select_ln51_195_fu_4775_p3;
        select_ln51_196_reg_6050 <= select_ln51_196_fu_4799_p3;
        select_ln51_197_reg_6055 <= select_ln51_197_fu_4823_p3;
        select_ln51_198_reg_6060 <= select_ln51_198_fu_4847_p3;
        select_ln51_199_reg_6065 <= select_ln51_199_fu_4871_p3;
        select_ln51_200_reg_6070 <= select_ln51_200_fu_4895_p3;
        select_ln51_201_reg_6075 <= select_ln51_201_fu_4919_p3;
        select_ln51_202_reg_6080 <= select_ln51_202_fu_4943_p3;
        select_ln51_203_reg_6085 <= select_ln51_203_fu_4967_p3;
        select_ln51_204_reg_6090 <= select_ln51_204_fu_4991_p3;
        select_ln51_205_reg_6095 <= select_ln51_205_fu_5015_p3;
        select_ln51_206_reg_6100 <= select_ln51_206_fu_5039_p3;
        select_ln51_207_reg_6105 <= select_ln51_207_fu_5063_p3;
        select_ln51_208_reg_6110 <= select_ln51_208_fu_5087_p3;
        select_ln51_209_reg_6115 <= select_ln51_209_fu_5111_p3;
        select_ln51_210_reg_6120 <= select_ln51_210_fu_5135_p3;
        select_ln51_211_reg_6125 <= select_ln51_211_fu_5159_p3;
        select_ln51_212_reg_6130 <= select_ln51_212_fu_5183_p3;
        select_ln51_213_reg_6135 <= select_ln51_213_fu_5207_p3;
        select_ln51_214_reg_6140 <= select_ln51_214_fu_5231_p3;
        select_ln51_215_reg_6145 <= select_ln51_215_fu_5255_p3;
        select_ln51_216_reg_6150 <= select_ln51_216_fu_5279_p3;
        select_ln51_217_reg_6155 <= select_ln51_217_fu_5303_p3;
        select_ln51_218_reg_6160 <= select_ln51_218_fu_5327_p3;
        select_ln51_219_reg_6165 <= select_ln51_219_fu_5351_p3;
        select_ln51_220_reg_6170 <= select_ln51_220_fu_5375_p3;
        select_ln51_221_reg_6175 <= select_ln51_221_fu_5399_p3;
        select_ln51_95_reg_5545 <= select_ln51_95_fu_2375_p3;
        select_ln51_96_reg_5550 <= select_ln51_96_fu_2399_p3;
        select_ln51_97_reg_5555 <= select_ln51_97_fu_2423_p3;
        select_ln51_98_reg_5560 <= select_ln51_98_fu_2447_p3;
        select_ln51_99_reg_5565 <= select_ln51_99_fu_2471_p3;
        select_ln51_reg_5540 <= select_ln51_fu_2351_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer3_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_read = 1'b1;
    end else begin
        layer2_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer3_out_blk_n = layer3_out_full_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer3_out_write = 1'b1;
    end else begin
        layer3_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer3_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_100_fu_2479_p2 = (($signed(trunc_ln44_97_fu_1115_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_101_fu_2503_p2 = (($signed(trunc_ln44_98_fu_1125_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_102_fu_2527_p2 = (($signed(trunc_ln44_99_fu_1135_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_103_fu_2551_p2 = (($signed(trunc_ln44_100_fu_1145_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_104_fu_2575_p2 = (($signed(trunc_ln44_101_fu_1155_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_105_fu_2599_p2 = (($signed(trunc_ln44_102_fu_1165_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_106_fu_2623_p2 = (($signed(trunc_ln44_103_fu_1175_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_107_fu_2647_p2 = (($signed(trunc_ln44_104_fu_1185_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_108_fu_2671_p2 = (($signed(trunc_ln44_105_fu_1195_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_109_fu_2695_p2 = (($signed(trunc_ln44_106_fu_1205_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_110_fu_2719_p2 = (($signed(trunc_ln44_107_fu_1215_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_111_fu_2743_p2 = (($signed(trunc_ln44_108_fu_1225_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_112_fu_2767_p2 = (($signed(trunc_ln44_109_fu_1235_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_113_fu_2791_p2 = (($signed(trunc_ln44_110_fu_1245_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_114_fu_2815_p2 = (($signed(trunc_ln44_111_fu_1255_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_115_fu_2839_p2 = (($signed(trunc_ln44_112_fu_1265_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_116_fu_2863_p2 = (($signed(trunc_ln44_113_fu_1275_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_117_fu_2887_p2 = (($signed(trunc_ln44_114_fu_1285_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_118_fu_2911_p2 = (($signed(trunc_ln44_115_fu_1295_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_119_fu_2935_p2 = (($signed(trunc_ln44_116_fu_1305_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_120_fu_2959_p2 = (($signed(trunc_ln44_117_fu_1315_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_121_fu_2983_p2 = (($signed(trunc_ln44_118_fu_1325_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_122_fu_3007_p2 = (($signed(trunc_ln44_119_fu_1335_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_123_fu_3031_p2 = (($signed(trunc_ln44_120_fu_1345_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_124_fu_3055_p2 = (($signed(trunc_ln44_121_fu_1355_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_125_fu_3079_p2 = (($signed(trunc_ln44_122_fu_1365_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_126_fu_3103_p2 = (($signed(trunc_ln44_123_fu_1375_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_127_fu_3127_p2 = (($signed(trunc_ln44_124_fu_1385_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_128_fu_3151_p2 = (($signed(trunc_ln44_125_fu_1395_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_129_fu_3175_p2 = (($signed(trunc_ln44_126_fu_1405_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_130_fu_3199_p2 = (($signed(trunc_ln44_127_fu_1415_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_131_fu_3223_p2 = (($signed(trunc_ln44_128_fu_1425_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_132_fu_3247_p2 = (($signed(trunc_ln44_129_fu_1435_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_133_fu_3271_p2 = (($signed(trunc_ln44_130_fu_1445_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_134_fu_3295_p2 = (($signed(trunc_ln44_131_fu_1455_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_135_fu_3319_p2 = (($signed(trunc_ln44_132_fu_1465_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_136_fu_3343_p2 = (($signed(trunc_ln44_133_fu_1475_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_137_fu_3367_p2 = (($signed(trunc_ln44_134_fu_1485_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_138_fu_3391_p2 = (($signed(trunc_ln44_135_fu_1495_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_139_fu_3415_p2 = (($signed(trunc_ln44_136_fu_1505_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_140_fu_3439_p2 = (($signed(trunc_ln44_137_fu_1515_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_141_fu_3463_p2 = (($signed(trunc_ln44_138_fu_1525_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_142_fu_3487_p2 = (($signed(trunc_ln44_139_fu_1535_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_143_fu_3511_p2 = (($signed(trunc_ln44_140_fu_1545_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_144_fu_3535_p2 = (($signed(trunc_ln44_141_fu_1555_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_145_fu_3559_p2 = (($signed(trunc_ln44_142_fu_1565_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_146_fu_3583_p2 = (($signed(trunc_ln44_143_fu_1575_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_147_fu_3607_p2 = (($signed(trunc_ln44_144_fu_1585_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_148_fu_3631_p2 = (($signed(trunc_ln44_145_fu_1595_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_149_fu_3655_p2 = (($signed(trunc_ln44_146_fu_1605_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_150_fu_3679_p2 = (($signed(trunc_ln44_147_fu_1615_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_151_fu_3703_p2 = (($signed(trunc_ln44_148_fu_1625_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_152_fu_3727_p2 = (($signed(trunc_ln44_149_fu_1635_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_153_fu_3751_p2 = (($signed(trunc_ln44_150_fu_1645_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_154_fu_3775_p2 = (($signed(trunc_ln44_151_fu_1655_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_155_fu_3799_p2 = (($signed(trunc_ln44_152_fu_1665_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_156_fu_3823_p2 = (($signed(trunc_ln44_153_fu_1675_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_157_fu_3847_p2 = (($signed(trunc_ln44_154_fu_1685_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_158_fu_3871_p2 = (($signed(trunc_ln44_155_fu_1695_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_159_fu_3895_p2 = (($signed(trunc_ln44_156_fu_1705_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_160_fu_3919_p2 = (($signed(trunc_ln44_157_fu_1715_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_161_fu_3943_p2 = (($signed(trunc_ln44_158_fu_1725_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_162_fu_3967_p2 = (($signed(trunc_ln44_159_fu_1735_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_163_fu_3991_p2 = (($signed(trunc_ln44_160_fu_1745_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_164_fu_4015_p2 = (($signed(trunc_ln44_161_fu_1755_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_165_fu_4039_p2 = (($signed(trunc_ln44_162_fu_1765_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_166_fu_4063_p2 = (($signed(trunc_ln44_163_fu_1775_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_167_fu_4087_p2 = (($signed(trunc_ln44_164_fu_1785_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_168_fu_4111_p2 = (($signed(trunc_ln44_165_fu_1795_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_169_fu_4135_p2 = (($signed(trunc_ln44_166_fu_1805_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_170_fu_4159_p2 = (($signed(trunc_ln44_167_fu_1815_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_171_fu_4183_p2 = (($signed(trunc_ln44_168_fu_1825_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_172_fu_4207_p2 = (($signed(trunc_ln44_169_fu_1835_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_173_fu_4231_p2 = (($signed(trunc_ln44_170_fu_1845_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_174_fu_4255_p2 = (($signed(trunc_ln44_171_fu_1855_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_175_fu_4279_p2 = (($signed(trunc_ln44_172_fu_1865_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_176_fu_4303_p2 = (($signed(trunc_ln44_173_fu_1875_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_177_fu_4327_p2 = (($signed(trunc_ln44_174_fu_1885_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_178_fu_4351_p2 = (($signed(trunc_ln44_175_fu_1895_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_179_fu_4375_p2 = (($signed(trunc_ln44_176_fu_1905_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_180_fu_4399_p2 = (($signed(trunc_ln44_177_fu_1915_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_181_fu_4423_p2 = (($signed(trunc_ln44_178_fu_1925_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_182_fu_4447_p2 = (($signed(trunc_ln44_179_fu_1935_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_183_fu_4471_p2 = (($signed(trunc_ln44_180_fu_1945_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_184_fu_4495_p2 = (($signed(trunc_ln44_181_fu_1955_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_185_fu_4519_p2 = (($signed(trunc_ln44_182_fu_1965_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_186_fu_4543_p2 = (($signed(trunc_ln44_183_fu_1975_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_187_fu_4567_p2 = (($signed(trunc_ln44_184_fu_1985_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_188_fu_4591_p2 = (($signed(trunc_ln44_185_fu_1995_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_189_fu_4615_p2 = (($signed(trunc_ln44_186_fu_2005_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_190_fu_4639_p2 = (($signed(trunc_ln44_187_fu_2015_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_191_fu_4663_p2 = (($signed(trunc_ln44_188_fu_2025_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_192_fu_4687_p2 = (($signed(trunc_ln44_189_fu_2035_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_193_fu_4711_p2 = (($signed(trunc_ln44_190_fu_2045_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_194_fu_4735_p2 = (($signed(trunc_ln44_191_fu_2055_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_195_fu_4759_p2 = (($signed(trunc_ln44_192_fu_2065_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_196_fu_4783_p2 = (($signed(trunc_ln44_193_fu_2075_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_197_fu_4807_p2 = (($signed(trunc_ln44_194_fu_2085_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_198_fu_4831_p2 = (($signed(trunc_ln44_195_fu_2095_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_199_fu_4855_p2 = (($signed(trunc_ln44_196_fu_2105_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_200_fu_4879_p2 = (($signed(trunc_ln44_197_fu_2115_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_201_fu_4903_p2 = (($signed(trunc_ln44_198_fu_2125_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_202_fu_4927_p2 = (($signed(trunc_ln44_199_fu_2135_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_203_fu_4951_p2 = (($signed(trunc_ln44_200_fu_2145_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_204_fu_4975_p2 = (($signed(trunc_ln44_201_fu_2155_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_205_fu_4999_p2 = (($signed(trunc_ln44_202_fu_2165_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_206_fu_5023_p2 = (($signed(trunc_ln44_203_fu_2175_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_207_fu_5047_p2 = (($signed(trunc_ln44_204_fu_2185_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_208_fu_5071_p2 = (($signed(trunc_ln44_205_fu_2195_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_209_fu_5095_p2 = (($signed(trunc_ln44_206_fu_2205_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_210_fu_5119_p2 = (($signed(trunc_ln44_207_fu_2215_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_211_fu_5143_p2 = (($signed(trunc_ln44_208_fu_2225_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_212_fu_5167_p2 = (($signed(trunc_ln44_209_fu_2235_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_213_fu_5191_p2 = (($signed(trunc_ln44_210_fu_2245_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_214_fu_5215_p2 = (($signed(trunc_ln44_211_fu_2255_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_215_fu_5239_p2 = (($signed(trunc_ln44_212_fu_2265_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_216_fu_5263_p2 = (($signed(trunc_ln44_213_fu_2275_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_217_fu_5287_p2 = (($signed(trunc_ln44_214_fu_2285_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_218_fu_5311_p2 = (($signed(trunc_ln44_215_fu_2295_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_219_fu_5335_p2 = (($signed(trunc_ln44_216_fu_2305_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_220_fu_5359_p2 = (($signed(trunc_ln44_217_fu_2315_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_221_fu_5383_p2 = (($signed(trunc_ln44_218_fu_2325_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_95_fu_2359_p2 = (($signed(trunc_ln44_s_fu_1065_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_96_fu_2383_p2 = (($signed(trunc_ln44_93_fu_1075_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_97_fu_2407_p2 = (($signed(trunc_ln44_94_fu_1085_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_98_fu_2431_p2 = (($signed(trunc_ln44_95_fu_1095_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_99_fu_2455_p2 = (($signed(trunc_ln44_96_fu_1105_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_2335_p2 = (($signed(trunc_ln44_fu_1061_p1) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign layer3_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_221_reg_6175}, {select_ln51_220_reg_6170}}, {select_ln51_219_reg_6165}}, {select_ln51_218_reg_6160}}, {select_ln51_217_reg_6155}}, {select_ln51_216_reg_6150}}, {select_ln51_215_reg_6145}}, {select_ln51_214_reg_6140}}, {select_ln51_213_reg_6135}}, {select_ln51_212_reg_6130}}, {select_ln51_211_reg_6125}}, {select_ln51_210_reg_6120}}, {select_ln51_209_reg_6115}}, {select_ln51_208_reg_6110}}, {select_ln51_207_reg_6105}}, {select_ln51_206_reg_6100}}, {select_ln51_205_reg_6095}}, {select_ln51_204_reg_6090}}, {select_ln51_203_reg_6085}}, {select_ln51_202_reg_6080}}, {select_ln51_201_reg_6075}}, {select_ln51_200_reg_6070}}, {select_ln51_199_reg_6065}}, {select_ln51_198_reg_6060}}, {select_ln51_197_reg_6055}}, {select_ln51_196_reg_6050}}, {select_ln51_195_reg_6045}}, {select_ln51_194_reg_6040}}, {select_ln51_193_reg_6035}}, {select_ln51_192_reg_6030}}, {select_ln51_191_reg_6025}}, 
    {select_ln51_190_reg_6020}}, {select_ln51_189_reg_6015}}, {select_ln51_188_reg_6010}}, {select_ln51_187_reg_6005}}, {select_ln51_186_reg_6000}}, {select_ln51_185_reg_5995}}, {select_ln51_184_reg_5990}}, {select_ln51_183_reg_5985}}, {select_ln51_182_reg_5980}}, {select_ln51_181_reg_5975}}, {select_ln51_180_reg_5970}}, {select_ln51_179_reg_5965}}, {select_ln51_178_reg_5960}}, {select_ln51_177_reg_5955}}, {select_ln51_176_reg_5950}}, {select_ln51_175_reg_5945}}, {select_ln51_174_reg_5940}}, {select_ln51_173_reg_5935}}, {select_ln51_172_reg_5930}}, {select_ln51_171_reg_5925}}, {select_ln51_170_reg_5920}}, {select_ln51_169_reg_5915}}, {select_ln51_168_reg_5910}}, {select_ln51_167_reg_5905}}, {select_ln51_166_reg_5900}}, {select_ln51_165_reg_5895}}, {select_ln51_164_reg_5890}}, {select_ln51_163_reg_5885}}, {select_ln51_162_reg_5880}}, {select_ln51_161_reg_5875}}, {select_ln51_160_reg_5870}}, {select_ln51_159_reg_5865}}, {select_ln51_158_reg_5860}}, {select_ln51_157_reg_5855}}, {select_ln51_156_reg_5850}}, {select_ln51_155_reg_5845}}, 
    {select_ln51_154_reg_5840}}, {select_ln51_153_reg_5835}}, {select_ln51_152_reg_5830}}, {select_ln51_151_reg_5825}}, {select_ln51_150_reg_5820}}, {select_ln51_149_reg_5815}}, {select_ln51_148_reg_5810}}, {select_ln51_147_reg_5805}}, {select_ln51_146_reg_5800}}, {select_ln51_145_reg_5795}}, {select_ln51_144_reg_5790}}, {select_ln51_143_reg_5785}}, {select_ln51_142_reg_5780}}, {select_ln51_141_reg_5775}}, {select_ln51_140_reg_5770}}, {select_ln51_139_reg_5765}}, {select_ln51_138_reg_5760}}, {select_ln51_137_reg_5755}}, {select_ln51_136_reg_5750}}, {select_ln51_135_reg_5745}}, {select_ln51_134_reg_5740}}, {select_ln51_133_reg_5735}}, {select_ln51_132_reg_5730}}, {select_ln51_131_reg_5725}}, {select_ln51_130_reg_5720}}, {select_ln51_129_reg_5715}}, {select_ln51_128_reg_5710}}, {select_ln51_127_reg_5705}}, {select_ln51_126_reg_5700}}, {select_ln51_125_reg_5695}}, {select_ln51_124_reg_5690}}, {select_ln51_123_reg_5685}}, {select_ln51_122_reg_5680}}, {select_ln51_121_reg_5675}}, {select_ln51_120_reg_5670}}, {select_ln51_119_reg_5665}}, 
    {select_ln51_118_reg_5660}}, {select_ln51_117_reg_5655}}, {select_ln51_116_reg_5650}}, {select_ln51_115_reg_5645}}, {select_ln51_114_reg_5640}}, {select_ln51_113_reg_5635}}, {select_ln51_112_reg_5630}}, {select_ln51_111_reg_5625}}, {select_ln51_110_reg_5620}}, {select_ln51_109_reg_5615}}, {select_ln51_108_reg_5610}}, {select_ln51_107_reg_5605}}, {select_ln51_106_reg_5600}}, {select_ln51_105_reg_5595}}, {select_ln51_104_reg_5590}}, {select_ln51_103_reg_5585}}, {select_ln51_102_reg_5580}}, {select_ln51_101_reg_5575}}, {select_ln51_100_reg_5570}}, {select_ln51_99_reg_5565}}, {select_ln51_98_reg_5560}}, {select_ln51_97_reg_5555}}, {select_ln51_96_reg_5550}}, {select_ln51_95_reg_5545}}, {select_ln51_reg_5540}};

assign select_ln51_100_fu_2495_p3 = ((icmp_ln51_100_fu_2479_p2[0:0] == 1'b1) ? trunc_ln52_97_fu_2485_p4 : 8'd0);

assign select_ln51_101_fu_2519_p3 = ((icmp_ln51_101_fu_2503_p2[0:0] == 1'b1) ? trunc_ln52_98_fu_2509_p4 : 8'd0);

assign select_ln51_102_fu_2543_p3 = ((icmp_ln51_102_fu_2527_p2[0:0] == 1'b1) ? trunc_ln52_99_fu_2533_p4 : 8'd0);

assign select_ln51_103_fu_2567_p3 = ((icmp_ln51_103_fu_2551_p2[0:0] == 1'b1) ? trunc_ln52_100_fu_2557_p4 : 8'd0);

assign select_ln51_104_fu_2591_p3 = ((icmp_ln51_104_fu_2575_p2[0:0] == 1'b1) ? trunc_ln52_101_fu_2581_p4 : 8'd0);

assign select_ln51_105_fu_2615_p3 = ((icmp_ln51_105_fu_2599_p2[0:0] == 1'b1) ? trunc_ln52_102_fu_2605_p4 : 8'd0);

assign select_ln51_106_fu_2639_p3 = ((icmp_ln51_106_fu_2623_p2[0:0] == 1'b1) ? trunc_ln52_103_fu_2629_p4 : 8'd0);

assign select_ln51_107_fu_2663_p3 = ((icmp_ln51_107_fu_2647_p2[0:0] == 1'b1) ? trunc_ln52_104_fu_2653_p4 : 8'd0);

assign select_ln51_108_fu_2687_p3 = ((icmp_ln51_108_fu_2671_p2[0:0] == 1'b1) ? trunc_ln52_105_fu_2677_p4 : 8'd0);

assign select_ln51_109_fu_2711_p3 = ((icmp_ln51_109_fu_2695_p2[0:0] == 1'b1) ? trunc_ln52_106_fu_2701_p4 : 8'd0);

assign select_ln51_110_fu_2735_p3 = ((icmp_ln51_110_fu_2719_p2[0:0] == 1'b1) ? trunc_ln52_107_fu_2725_p4 : 8'd0);

assign select_ln51_111_fu_2759_p3 = ((icmp_ln51_111_fu_2743_p2[0:0] == 1'b1) ? trunc_ln52_108_fu_2749_p4 : 8'd0);

assign select_ln51_112_fu_2783_p3 = ((icmp_ln51_112_fu_2767_p2[0:0] == 1'b1) ? trunc_ln52_109_fu_2773_p4 : 8'd0);

assign select_ln51_113_fu_2807_p3 = ((icmp_ln51_113_fu_2791_p2[0:0] == 1'b1) ? trunc_ln52_110_fu_2797_p4 : 8'd0);

assign select_ln51_114_fu_2831_p3 = ((icmp_ln51_114_fu_2815_p2[0:0] == 1'b1) ? trunc_ln52_111_fu_2821_p4 : 8'd0);

assign select_ln51_115_fu_2855_p3 = ((icmp_ln51_115_fu_2839_p2[0:0] == 1'b1) ? trunc_ln52_112_fu_2845_p4 : 8'd0);

assign select_ln51_116_fu_2879_p3 = ((icmp_ln51_116_fu_2863_p2[0:0] == 1'b1) ? trunc_ln52_113_fu_2869_p4 : 8'd0);

assign select_ln51_117_fu_2903_p3 = ((icmp_ln51_117_fu_2887_p2[0:0] == 1'b1) ? trunc_ln52_114_fu_2893_p4 : 8'd0);

assign select_ln51_118_fu_2927_p3 = ((icmp_ln51_118_fu_2911_p2[0:0] == 1'b1) ? trunc_ln52_115_fu_2917_p4 : 8'd0);

assign select_ln51_119_fu_2951_p3 = ((icmp_ln51_119_fu_2935_p2[0:0] == 1'b1) ? trunc_ln52_116_fu_2941_p4 : 8'd0);

assign select_ln51_120_fu_2975_p3 = ((icmp_ln51_120_fu_2959_p2[0:0] == 1'b1) ? trunc_ln52_117_fu_2965_p4 : 8'd0);

assign select_ln51_121_fu_2999_p3 = ((icmp_ln51_121_fu_2983_p2[0:0] == 1'b1) ? trunc_ln52_118_fu_2989_p4 : 8'd0);

assign select_ln51_122_fu_3023_p3 = ((icmp_ln51_122_fu_3007_p2[0:0] == 1'b1) ? trunc_ln52_119_fu_3013_p4 : 8'd0);

assign select_ln51_123_fu_3047_p3 = ((icmp_ln51_123_fu_3031_p2[0:0] == 1'b1) ? trunc_ln52_120_fu_3037_p4 : 8'd0);

assign select_ln51_124_fu_3071_p3 = ((icmp_ln51_124_fu_3055_p2[0:0] == 1'b1) ? trunc_ln52_121_fu_3061_p4 : 8'd0);

assign select_ln51_125_fu_3095_p3 = ((icmp_ln51_125_fu_3079_p2[0:0] == 1'b1) ? trunc_ln52_122_fu_3085_p4 : 8'd0);

assign select_ln51_126_fu_3119_p3 = ((icmp_ln51_126_fu_3103_p2[0:0] == 1'b1) ? trunc_ln52_123_fu_3109_p4 : 8'd0);

assign select_ln51_127_fu_3143_p3 = ((icmp_ln51_127_fu_3127_p2[0:0] == 1'b1) ? trunc_ln52_124_fu_3133_p4 : 8'd0);

assign select_ln51_128_fu_3167_p3 = ((icmp_ln51_128_fu_3151_p2[0:0] == 1'b1) ? trunc_ln52_125_fu_3157_p4 : 8'd0);

assign select_ln51_129_fu_3191_p3 = ((icmp_ln51_129_fu_3175_p2[0:0] == 1'b1) ? trunc_ln52_126_fu_3181_p4 : 8'd0);

assign select_ln51_130_fu_3215_p3 = ((icmp_ln51_130_fu_3199_p2[0:0] == 1'b1) ? trunc_ln52_127_fu_3205_p4 : 8'd0);

assign select_ln51_131_fu_3239_p3 = ((icmp_ln51_131_fu_3223_p2[0:0] == 1'b1) ? trunc_ln52_128_fu_3229_p4 : 8'd0);

assign select_ln51_132_fu_3263_p3 = ((icmp_ln51_132_fu_3247_p2[0:0] == 1'b1) ? trunc_ln52_129_fu_3253_p4 : 8'd0);

assign select_ln51_133_fu_3287_p3 = ((icmp_ln51_133_fu_3271_p2[0:0] == 1'b1) ? trunc_ln52_130_fu_3277_p4 : 8'd0);

assign select_ln51_134_fu_3311_p3 = ((icmp_ln51_134_fu_3295_p2[0:0] == 1'b1) ? trunc_ln52_131_fu_3301_p4 : 8'd0);

assign select_ln51_135_fu_3335_p3 = ((icmp_ln51_135_fu_3319_p2[0:0] == 1'b1) ? trunc_ln52_132_fu_3325_p4 : 8'd0);

assign select_ln51_136_fu_3359_p3 = ((icmp_ln51_136_fu_3343_p2[0:0] == 1'b1) ? trunc_ln52_133_fu_3349_p4 : 8'd0);

assign select_ln51_137_fu_3383_p3 = ((icmp_ln51_137_fu_3367_p2[0:0] == 1'b1) ? trunc_ln52_134_fu_3373_p4 : 8'd0);

assign select_ln51_138_fu_3407_p3 = ((icmp_ln51_138_fu_3391_p2[0:0] == 1'b1) ? trunc_ln52_135_fu_3397_p4 : 8'd0);

assign select_ln51_139_fu_3431_p3 = ((icmp_ln51_139_fu_3415_p2[0:0] == 1'b1) ? trunc_ln52_136_fu_3421_p4 : 8'd0);

assign select_ln51_140_fu_3455_p3 = ((icmp_ln51_140_fu_3439_p2[0:0] == 1'b1) ? trunc_ln52_137_fu_3445_p4 : 8'd0);

assign select_ln51_141_fu_3479_p3 = ((icmp_ln51_141_fu_3463_p2[0:0] == 1'b1) ? trunc_ln52_138_fu_3469_p4 : 8'd0);

assign select_ln51_142_fu_3503_p3 = ((icmp_ln51_142_fu_3487_p2[0:0] == 1'b1) ? trunc_ln52_139_fu_3493_p4 : 8'd0);

assign select_ln51_143_fu_3527_p3 = ((icmp_ln51_143_fu_3511_p2[0:0] == 1'b1) ? trunc_ln52_140_fu_3517_p4 : 8'd0);

assign select_ln51_144_fu_3551_p3 = ((icmp_ln51_144_fu_3535_p2[0:0] == 1'b1) ? trunc_ln52_141_fu_3541_p4 : 8'd0);

assign select_ln51_145_fu_3575_p3 = ((icmp_ln51_145_fu_3559_p2[0:0] == 1'b1) ? trunc_ln52_142_fu_3565_p4 : 8'd0);

assign select_ln51_146_fu_3599_p3 = ((icmp_ln51_146_fu_3583_p2[0:0] == 1'b1) ? trunc_ln52_143_fu_3589_p4 : 8'd0);

assign select_ln51_147_fu_3623_p3 = ((icmp_ln51_147_fu_3607_p2[0:0] == 1'b1) ? trunc_ln52_144_fu_3613_p4 : 8'd0);

assign select_ln51_148_fu_3647_p3 = ((icmp_ln51_148_fu_3631_p2[0:0] == 1'b1) ? trunc_ln52_145_fu_3637_p4 : 8'd0);

assign select_ln51_149_fu_3671_p3 = ((icmp_ln51_149_fu_3655_p2[0:0] == 1'b1) ? trunc_ln52_146_fu_3661_p4 : 8'd0);

assign select_ln51_150_fu_3695_p3 = ((icmp_ln51_150_fu_3679_p2[0:0] == 1'b1) ? trunc_ln52_147_fu_3685_p4 : 8'd0);

assign select_ln51_151_fu_3719_p3 = ((icmp_ln51_151_fu_3703_p2[0:0] == 1'b1) ? trunc_ln52_148_fu_3709_p4 : 8'd0);

assign select_ln51_152_fu_3743_p3 = ((icmp_ln51_152_fu_3727_p2[0:0] == 1'b1) ? trunc_ln52_149_fu_3733_p4 : 8'd0);

assign select_ln51_153_fu_3767_p3 = ((icmp_ln51_153_fu_3751_p2[0:0] == 1'b1) ? trunc_ln52_150_fu_3757_p4 : 8'd0);

assign select_ln51_154_fu_3791_p3 = ((icmp_ln51_154_fu_3775_p2[0:0] == 1'b1) ? trunc_ln52_151_fu_3781_p4 : 8'd0);

assign select_ln51_155_fu_3815_p3 = ((icmp_ln51_155_fu_3799_p2[0:0] == 1'b1) ? trunc_ln52_152_fu_3805_p4 : 8'd0);

assign select_ln51_156_fu_3839_p3 = ((icmp_ln51_156_fu_3823_p2[0:0] == 1'b1) ? trunc_ln52_153_fu_3829_p4 : 8'd0);

assign select_ln51_157_fu_3863_p3 = ((icmp_ln51_157_fu_3847_p2[0:0] == 1'b1) ? trunc_ln52_154_fu_3853_p4 : 8'd0);

assign select_ln51_158_fu_3887_p3 = ((icmp_ln51_158_fu_3871_p2[0:0] == 1'b1) ? trunc_ln52_155_fu_3877_p4 : 8'd0);

assign select_ln51_159_fu_3911_p3 = ((icmp_ln51_159_fu_3895_p2[0:0] == 1'b1) ? trunc_ln52_156_fu_3901_p4 : 8'd0);

assign select_ln51_160_fu_3935_p3 = ((icmp_ln51_160_fu_3919_p2[0:0] == 1'b1) ? trunc_ln52_157_fu_3925_p4 : 8'd0);

assign select_ln51_161_fu_3959_p3 = ((icmp_ln51_161_fu_3943_p2[0:0] == 1'b1) ? trunc_ln52_158_fu_3949_p4 : 8'd0);

assign select_ln51_162_fu_3983_p3 = ((icmp_ln51_162_fu_3967_p2[0:0] == 1'b1) ? trunc_ln52_159_fu_3973_p4 : 8'd0);

assign select_ln51_163_fu_4007_p3 = ((icmp_ln51_163_fu_3991_p2[0:0] == 1'b1) ? trunc_ln52_160_fu_3997_p4 : 8'd0);

assign select_ln51_164_fu_4031_p3 = ((icmp_ln51_164_fu_4015_p2[0:0] == 1'b1) ? trunc_ln52_161_fu_4021_p4 : 8'd0);

assign select_ln51_165_fu_4055_p3 = ((icmp_ln51_165_fu_4039_p2[0:0] == 1'b1) ? trunc_ln52_162_fu_4045_p4 : 8'd0);

assign select_ln51_166_fu_4079_p3 = ((icmp_ln51_166_fu_4063_p2[0:0] == 1'b1) ? trunc_ln52_163_fu_4069_p4 : 8'd0);

assign select_ln51_167_fu_4103_p3 = ((icmp_ln51_167_fu_4087_p2[0:0] == 1'b1) ? trunc_ln52_164_fu_4093_p4 : 8'd0);

assign select_ln51_168_fu_4127_p3 = ((icmp_ln51_168_fu_4111_p2[0:0] == 1'b1) ? trunc_ln52_165_fu_4117_p4 : 8'd0);

assign select_ln51_169_fu_4151_p3 = ((icmp_ln51_169_fu_4135_p2[0:0] == 1'b1) ? trunc_ln52_166_fu_4141_p4 : 8'd0);

assign select_ln51_170_fu_4175_p3 = ((icmp_ln51_170_fu_4159_p2[0:0] == 1'b1) ? trunc_ln52_167_fu_4165_p4 : 8'd0);

assign select_ln51_171_fu_4199_p3 = ((icmp_ln51_171_fu_4183_p2[0:0] == 1'b1) ? trunc_ln52_168_fu_4189_p4 : 8'd0);

assign select_ln51_172_fu_4223_p3 = ((icmp_ln51_172_fu_4207_p2[0:0] == 1'b1) ? trunc_ln52_169_fu_4213_p4 : 8'd0);

assign select_ln51_173_fu_4247_p3 = ((icmp_ln51_173_fu_4231_p2[0:0] == 1'b1) ? trunc_ln52_170_fu_4237_p4 : 8'd0);

assign select_ln51_174_fu_4271_p3 = ((icmp_ln51_174_fu_4255_p2[0:0] == 1'b1) ? trunc_ln52_171_fu_4261_p4 : 8'd0);

assign select_ln51_175_fu_4295_p3 = ((icmp_ln51_175_fu_4279_p2[0:0] == 1'b1) ? trunc_ln52_172_fu_4285_p4 : 8'd0);

assign select_ln51_176_fu_4319_p3 = ((icmp_ln51_176_fu_4303_p2[0:0] == 1'b1) ? trunc_ln52_173_fu_4309_p4 : 8'd0);

assign select_ln51_177_fu_4343_p3 = ((icmp_ln51_177_fu_4327_p2[0:0] == 1'b1) ? trunc_ln52_174_fu_4333_p4 : 8'd0);

assign select_ln51_178_fu_4367_p3 = ((icmp_ln51_178_fu_4351_p2[0:0] == 1'b1) ? trunc_ln52_175_fu_4357_p4 : 8'd0);

assign select_ln51_179_fu_4391_p3 = ((icmp_ln51_179_fu_4375_p2[0:0] == 1'b1) ? trunc_ln52_176_fu_4381_p4 : 8'd0);

assign select_ln51_180_fu_4415_p3 = ((icmp_ln51_180_fu_4399_p2[0:0] == 1'b1) ? trunc_ln52_177_fu_4405_p4 : 8'd0);

assign select_ln51_181_fu_4439_p3 = ((icmp_ln51_181_fu_4423_p2[0:0] == 1'b1) ? trunc_ln52_178_fu_4429_p4 : 8'd0);

assign select_ln51_182_fu_4463_p3 = ((icmp_ln51_182_fu_4447_p2[0:0] == 1'b1) ? trunc_ln52_179_fu_4453_p4 : 8'd0);

assign select_ln51_183_fu_4487_p3 = ((icmp_ln51_183_fu_4471_p2[0:0] == 1'b1) ? trunc_ln52_180_fu_4477_p4 : 8'd0);

assign select_ln51_184_fu_4511_p3 = ((icmp_ln51_184_fu_4495_p2[0:0] == 1'b1) ? trunc_ln52_181_fu_4501_p4 : 8'd0);

assign select_ln51_185_fu_4535_p3 = ((icmp_ln51_185_fu_4519_p2[0:0] == 1'b1) ? trunc_ln52_182_fu_4525_p4 : 8'd0);

assign select_ln51_186_fu_4559_p3 = ((icmp_ln51_186_fu_4543_p2[0:0] == 1'b1) ? trunc_ln52_183_fu_4549_p4 : 8'd0);

assign select_ln51_187_fu_4583_p3 = ((icmp_ln51_187_fu_4567_p2[0:0] == 1'b1) ? trunc_ln52_184_fu_4573_p4 : 8'd0);

assign select_ln51_188_fu_4607_p3 = ((icmp_ln51_188_fu_4591_p2[0:0] == 1'b1) ? trunc_ln52_185_fu_4597_p4 : 8'd0);

assign select_ln51_189_fu_4631_p3 = ((icmp_ln51_189_fu_4615_p2[0:0] == 1'b1) ? trunc_ln52_186_fu_4621_p4 : 8'd0);

assign select_ln51_190_fu_4655_p3 = ((icmp_ln51_190_fu_4639_p2[0:0] == 1'b1) ? trunc_ln52_187_fu_4645_p4 : 8'd0);

assign select_ln51_191_fu_4679_p3 = ((icmp_ln51_191_fu_4663_p2[0:0] == 1'b1) ? trunc_ln52_188_fu_4669_p4 : 8'd0);

assign select_ln51_192_fu_4703_p3 = ((icmp_ln51_192_fu_4687_p2[0:0] == 1'b1) ? trunc_ln52_189_fu_4693_p4 : 8'd0);

assign select_ln51_193_fu_4727_p3 = ((icmp_ln51_193_fu_4711_p2[0:0] == 1'b1) ? trunc_ln52_190_fu_4717_p4 : 8'd0);

assign select_ln51_194_fu_4751_p3 = ((icmp_ln51_194_fu_4735_p2[0:0] == 1'b1) ? trunc_ln52_191_fu_4741_p4 : 8'd0);

assign select_ln51_195_fu_4775_p3 = ((icmp_ln51_195_fu_4759_p2[0:0] == 1'b1) ? trunc_ln52_192_fu_4765_p4 : 8'd0);

assign select_ln51_196_fu_4799_p3 = ((icmp_ln51_196_fu_4783_p2[0:0] == 1'b1) ? trunc_ln52_193_fu_4789_p4 : 8'd0);

assign select_ln51_197_fu_4823_p3 = ((icmp_ln51_197_fu_4807_p2[0:0] == 1'b1) ? trunc_ln52_194_fu_4813_p4 : 8'd0);

assign select_ln51_198_fu_4847_p3 = ((icmp_ln51_198_fu_4831_p2[0:0] == 1'b1) ? trunc_ln52_195_fu_4837_p4 : 8'd0);

assign select_ln51_199_fu_4871_p3 = ((icmp_ln51_199_fu_4855_p2[0:0] == 1'b1) ? trunc_ln52_196_fu_4861_p4 : 8'd0);

assign select_ln51_200_fu_4895_p3 = ((icmp_ln51_200_fu_4879_p2[0:0] == 1'b1) ? trunc_ln52_197_fu_4885_p4 : 8'd0);

assign select_ln51_201_fu_4919_p3 = ((icmp_ln51_201_fu_4903_p2[0:0] == 1'b1) ? trunc_ln52_198_fu_4909_p4 : 8'd0);

assign select_ln51_202_fu_4943_p3 = ((icmp_ln51_202_fu_4927_p2[0:0] == 1'b1) ? trunc_ln52_199_fu_4933_p4 : 8'd0);

assign select_ln51_203_fu_4967_p3 = ((icmp_ln51_203_fu_4951_p2[0:0] == 1'b1) ? trunc_ln52_200_fu_4957_p4 : 8'd0);

assign select_ln51_204_fu_4991_p3 = ((icmp_ln51_204_fu_4975_p2[0:0] == 1'b1) ? trunc_ln52_201_fu_4981_p4 : 8'd0);

assign select_ln51_205_fu_5015_p3 = ((icmp_ln51_205_fu_4999_p2[0:0] == 1'b1) ? trunc_ln52_202_fu_5005_p4 : 8'd0);

assign select_ln51_206_fu_5039_p3 = ((icmp_ln51_206_fu_5023_p2[0:0] == 1'b1) ? trunc_ln52_203_fu_5029_p4 : 8'd0);

assign select_ln51_207_fu_5063_p3 = ((icmp_ln51_207_fu_5047_p2[0:0] == 1'b1) ? trunc_ln52_204_fu_5053_p4 : 8'd0);

assign select_ln51_208_fu_5087_p3 = ((icmp_ln51_208_fu_5071_p2[0:0] == 1'b1) ? trunc_ln52_205_fu_5077_p4 : 8'd0);

assign select_ln51_209_fu_5111_p3 = ((icmp_ln51_209_fu_5095_p2[0:0] == 1'b1) ? trunc_ln52_206_fu_5101_p4 : 8'd0);

assign select_ln51_210_fu_5135_p3 = ((icmp_ln51_210_fu_5119_p2[0:0] == 1'b1) ? trunc_ln52_207_fu_5125_p4 : 8'd0);

assign select_ln51_211_fu_5159_p3 = ((icmp_ln51_211_fu_5143_p2[0:0] == 1'b1) ? trunc_ln52_208_fu_5149_p4 : 8'd0);

assign select_ln51_212_fu_5183_p3 = ((icmp_ln51_212_fu_5167_p2[0:0] == 1'b1) ? trunc_ln52_209_fu_5173_p4 : 8'd0);

assign select_ln51_213_fu_5207_p3 = ((icmp_ln51_213_fu_5191_p2[0:0] == 1'b1) ? trunc_ln52_210_fu_5197_p4 : 8'd0);

assign select_ln51_214_fu_5231_p3 = ((icmp_ln51_214_fu_5215_p2[0:0] == 1'b1) ? trunc_ln52_211_fu_5221_p4 : 8'd0);

assign select_ln51_215_fu_5255_p3 = ((icmp_ln51_215_fu_5239_p2[0:0] == 1'b1) ? trunc_ln52_212_fu_5245_p4 : 8'd0);

assign select_ln51_216_fu_5279_p3 = ((icmp_ln51_216_fu_5263_p2[0:0] == 1'b1) ? trunc_ln52_213_fu_5269_p4 : 8'd0);

assign select_ln51_217_fu_5303_p3 = ((icmp_ln51_217_fu_5287_p2[0:0] == 1'b1) ? trunc_ln52_214_fu_5293_p4 : 8'd0);

assign select_ln51_218_fu_5327_p3 = ((icmp_ln51_218_fu_5311_p2[0:0] == 1'b1) ? trunc_ln52_215_fu_5317_p4 : 8'd0);

assign select_ln51_219_fu_5351_p3 = ((icmp_ln51_219_fu_5335_p2[0:0] == 1'b1) ? trunc_ln52_216_fu_5341_p4 : 8'd0);

assign select_ln51_220_fu_5375_p3 = ((icmp_ln51_220_fu_5359_p2[0:0] == 1'b1) ? trunc_ln52_217_fu_5365_p4 : 8'd0);

assign select_ln51_221_fu_5399_p3 = ((icmp_ln51_221_fu_5383_p2[0:0] == 1'b1) ? trunc_ln52_218_fu_5389_p4 : 8'd0);

assign select_ln51_95_fu_2375_p3 = ((icmp_ln51_95_fu_2359_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_2365_p4 : 8'd0);

assign select_ln51_96_fu_2399_p3 = ((icmp_ln51_96_fu_2383_p2[0:0] == 1'b1) ? trunc_ln52_93_fu_2389_p4 : 8'd0);

assign select_ln51_97_fu_2423_p3 = ((icmp_ln51_97_fu_2407_p2[0:0] == 1'b1) ? trunc_ln52_94_fu_2413_p4 : 8'd0);

assign select_ln51_98_fu_2447_p3 = ((icmp_ln51_98_fu_2431_p2[0:0] == 1'b1) ? trunc_ln52_95_fu_2437_p4 : 8'd0);

assign select_ln51_99_fu_2471_p3 = ((icmp_ln51_99_fu_2455_p2[0:0] == 1'b1) ? trunc_ln52_96_fu_2461_p4 : 8'd0);

assign select_ln51_fu_2351_p3 = ((icmp_ln51_fu_2335_p2[0:0] == 1'b1) ? trunc_ln4_fu_2341_p4 : 8'd0);

assign start_out = real_start;

assign trunc_ln44_100_fu_1145_p4 = {{layer2_out_dout[179:162]}};

assign trunc_ln44_101_fu_1155_p4 = {{layer2_out_dout[197:180]}};

assign trunc_ln44_102_fu_1165_p4 = {{layer2_out_dout[215:198]}};

assign trunc_ln44_103_fu_1175_p4 = {{layer2_out_dout[233:216]}};

assign trunc_ln44_104_fu_1185_p4 = {{layer2_out_dout[251:234]}};

assign trunc_ln44_105_fu_1195_p4 = {{layer2_out_dout[269:252]}};

assign trunc_ln44_106_fu_1205_p4 = {{layer2_out_dout[287:270]}};

assign trunc_ln44_107_fu_1215_p4 = {{layer2_out_dout[305:288]}};

assign trunc_ln44_108_fu_1225_p4 = {{layer2_out_dout[323:306]}};

assign trunc_ln44_109_fu_1235_p4 = {{layer2_out_dout[341:324]}};

assign trunc_ln44_110_fu_1245_p4 = {{layer2_out_dout[359:342]}};

assign trunc_ln44_111_fu_1255_p4 = {{layer2_out_dout[377:360]}};

assign trunc_ln44_112_fu_1265_p4 = {{layer2_out_dout[395:378]}};

assign trunc_ln44_113_fu_1275_p4 = {{layer2_out_dout[413:396]}};

assign trunc_ln44_114_fu_1285_p4 = {{layer2_out_dout[431:414]}};

assign trunc_ln44_115_fu_1295_p4 = {{layer2_out_dout[449:432]}};

assign trunc_ln44_116_fu_1305_p4 = {{layer2_out_dout[467:450]}};

assign trunc_ln44_117_fu_1315_p4 = {{layer2_out_dout[485:468]}};

assign trunc_ln44_118_fu_1325_p4 = {{layer2_out_dout[503:486]}};

assign trunc_ln44_119_fu_1335_p4 = {{layer2_out_dout[521:504]}};

assign trunc_ln44_120_fu_1345_p4 = {{layer2_out_dout[539:522]}};

assign trunc_ln44_121_fu_1355_p4 = {{layer2_out_dout[557:540]}};

assign trunc_ln44_122_fu_1365_p4 = {{layer2_out_dout[575:558]}};

assign trunc_ln44_123_fu_1375_p4 = {{layer2_out_dout[593:576]}};

assign trunc_ln44_124_fu_1385_p4 = {{layer2_out_dout[611:594]}};

assign trunc_ln44_125_fu_1395_p4 = {{layer2_out_dout[629:612]}};

assign trunc_ln44_126_fu_1405_p4 = {{layer2_out_dout[647:630]}};

assign trunc_ln44_127_fu_1415_p4 = {{layer2_out_dout[665:648]}};

assign trunc_ln44_128_fu_1425_p4 = {{layer2_out_dout[683:666]}};

assign trunc_ln44_129_fu_1435_p4 = {{layer2_out_dout[701:684]}};

assign trunc_ln44_130_fu_1445_p4 = {{layer2_out_dout[719:702]}};

assign trunc_ln44_131_fu_1455_p4 = {{layer2_out_dout[737:720]}};

assign trunc_ln44_132_fu_1465_p4 = {{layer2_out_dout[755:738]}};

assign trunc_ln44_133_fu_1475_p4 = {{layer2_out_dout[773:756]}};

assign trunc_ln44_134_fu_1485_p4 = {{layer2_out_dout[791:774]}};

assign trunc_ln44_135_fu_1495_p4 = {{layer2_out_dout[809:792]}};

assign trunc_ln44_136_fu_1505_p4 = {{layer2_out_dout[827:810]}};

assign trunc_ln44_137_fu_1515_p4 = {{layer2_out_dout[845:828]}};

assign trunc_ln44_138_fu_1525_p4 = {{layer2_out_dout[863:846]}};

assign trunc_ln44_139_fu_1535_p4 = {{layer2_out_dout[881:864]}};

assign trunc_ln44_140_fu_1545_p4 = {{layer2_out_dout[899:882]}};

assign trunc_ln44_141_fu_1555_p4 = {{layer2_out_dout[917:900]}};

assign trunc_ln44_142_fu_1565_p4 = {{layer2_out_dout[935:918]}};

assign trunc_ln44_143_fu_1575_p4 = {{layer2_out_dout[953:936]}};

assign trunc_ln44_144_fu_1585_p4 = {{layer2_out_dout[971:954]}};

assign trunc_ln44_145_fu_1595_p4 = {{layer2_out_dout[989:972]}};

assign trunc_ln44_146_fu_1605_p4 = {{layer2_out_dout[1007:990]}};

assign trunc_ln44_147_fu_1615_p4 = {{layer2_out_dout[1025:1008]}};

assign trunc_ln44_148_fu_1625_p4 = {{layer2_out_dout[1043:1026]}};

assign trunc_ln44_149_fu_1635_p4 = {{layer2_out_dout[1061:1044]}};

assign trunc_ln44_150_fu_1645_p4 = {{layer2_out_dout[1079:1062]}};

assign trunc_ln44_151_fu_1655_p4 = {{layer2_out_dout[1097:1080]}};

assign trunc_ln44_152_fu_1665_p4 = {{layer2_out_dout[1115:1098]}};

assign trunc_ln44_153_fu_1675_p4 = {{layer2_out_dout[1133:1116]}};

assign trunc_ln44_154_fu_1685_p4 = {{layer2_out_dout[1151:1134]}};

assign trunc_ln44_155_fu_1695_p4 = {{layer2_out_dout[1169:1152]}};

assign trunc_ln44_156_fu_1705_p4 = {{layer2_out_dout[1187:1170]}};

assign trunc_ln44_157_fu_1715_p4 = {{layer2_out_dout[1205:1188]}};

assign trunc_ln44_158_fu_1725_p4 = {{layer2_out_dout[1223:1206]}};

assign trunc_ln44_159_fu_1735_p4 = {{layer2_out_dout[1241:1224]}};

assign trunc_ln44_160_fu_1745_p4 = {{layer2_out_dout[1259:1242]}};

assign trunc_ln44_161_fu_1755_p4 = {{layer2_out_dout[1277:1260]}};

assign trunc_ln44_162_fu_1765_p4 = {{layer2_out_dout[1295:1278]}};

assign trunc_ln44_163_fu_1775_p4 = {{layer2_out_dout[1313:1296]}};

assign trunc_ln44_164_fu_1785_p4 = {{layer2_out_dout[1331:1314]}};

assign trunc_ln44_165_fu_1795_p4 = {{layer2_out_dout[1349:1332]}};

assign trunc_ln44_166_fu_1805_p4 = {{layer2_out_dout[1367:1350]}};

assign trunc_ln44_167_fu_1815_p4 = {{layer2_out_dout[1385:1368]}};

assign trunc_ln44_168_fu_1825_p4 = {{layer2_out_dout[1403:1386]}};

assign trunc_ln44_169_fu_1835_p4 = {{layer2_out_dout[1421:1404]}};

assign trunc_ln44_170_fu_1845_p4 = {{layer2_out_dout[1439:1422]}};

assign trunc_ln44_171_fu_1855_p4 = {{layer2_out_dout[1457:1440]}};

assign trunc_ln44_172_fu_1865_p4 = {{layer2_out_dout[1475:1458]}};

assign trunc_ln44_173_fu_1875_p4 = {{layer2_out_dout[1493:1476]}};

assign trunc_ln44_174_fu_1885_p4 = {{layer2_out_dout[1511:1494]}};

assign trunc_ln44_175_fu_1895_p4 = {{layer2_out_dout[1529:1512]}};

assign trunc_ln44_176_fu_1905_p4 = {{layer2_out_dout[1547:1530]}};

assign trunc_ln44_177_fu_1915_p4 = {{layer2_out_dout[1565:1548]}};

assign trunc_ln44_178_fu_1925_p4 = {{layer2_out_dout[1583:1566]}};

assign trunc_ln44_179_fu_1935_p4 = {{layer2_out_dout[1601:1584]}};

assign trunc_ln44_180_fu_1945_p4 = {{layer2_out_dout[1619:1602]}};

assign trunc_ln44_181_fu_1955_p4 = {{layer2_out_dout[1637:1620]}};

assign trunc_ln44_182_fu_1965_p4 = {{layer2_out_dout[1655:1638]}};

assign trunc_ln44_183_fu_1975_p4 = {{layer2_out_dout[1673:1656]}};

assign trunc_ln44_184_fu_1985_p4 = {{layer2_out_dout[1691:1674]}};

assign trunc_ln44_185_fu_1995_p4 = {{layer2_out_dout[1709:1692]}};

assign trunc_ln44_186_fu_2005_p4 = {{layer2_out_dout[1727:1710]}};

assign trunc_ln44_187_fu_2015_p4 = {{layer2_out_dout[1745:1728]}};

assign trunc_ln44_188_fu_2025_p4 = {{layer2_out_dout[1763:1746]}};

assign trunc_ln44_189_fu_2035_p4 = {{layer2_out_dout[1781:1764]}};

assign trunc_ln44_190_fu_2045_p4 = {{layer2_out_dout[1799:1782]}};

assign trunc_ln44_191_fu_2055_p4 = {{layer2_out_dout[1817:1800]}};

assign trunc_ln44_192_fu_2065_p4 = {{layer2_out_dout[1835:1818]}};

assign trunc_ln44_193_fu_2075_p4 = {{layer2_out_dout[1853:1836]}};

assign trunc_ln44_194_fu_2085_p4 = {{layer2_out_dout[1871:1854]}};

assign trunc_ln44_195_fu_2095_p4 = {{layer2_out_dout[1889:1872]}};

assign trunc_ln44_196_fu_2105_p4 = {{layer2_out_dout[1907:1890]}};

assign trunc_ln44_197_fu_2115_p4 = {{layer2_out_dout[1925:1908]}};

assign trunc_ln44_198_fu_2125_p4 = {{layer2_out_dout[1943:1926]}};

assign trunc_ln44_199_fu_2135_p4 = {{layer2_out_dout[1961:1944]}};

assign trunc_ln44_200_fu_2145_p4 = {{layer2_out_dout[1979:1962]}};

assign trunc_ln44_201_fu_2155_p4 = {{layer2_out_dout[1997:1980]}};

assign trunc_ln44_202_fu_2165_p4 = {{layer2_out_dout[2015:1998]}};

assign trunc_ln44_203_fu_2175_p4 = {{layer2_out_dout[2033:2016]}};

assign trunc_ln44_204_fu_2185_p4 = {{layer2_out_dout[2051:2034]}};

assign trunc_ln44_205_fu_2195_p4 = {{layer2_out_dout[2069:2052]}};

assign trunc_ln44_206_fu_2205_p4 = {{layer2_out_dout[2087:2070]}};

assign trunc_ln44_207_fu_2215_p4 = {{layer2_out_dout[2105:2088]}};

assign trunc_ln44_208_fu_2225_p4 = {{layer2_out_dout[2123:2106]}};

assign trunc_ln44_209_fu_2235_p4 = {{layer2_out_dout[2141:2124]}};

assign trunc_ln44_210_fu_2245_p4 = {{layer2_out_dout[2159:2142]}};

assign trunc_ln44_211_fu_2255_p4 = {{layer2_out_dout[2177:2160]}};

assign trunc_ln44_212_fu_2265_p4 = {{layer2_out_dout[2195:2178]}};

assign trunc_ln44_213_fu_2275_p4 = {{layer2_out_dout[2213:2196]}};

assign trunc_ln44_214_fu_2285_p4 = {{layer2_out_dout[2231:2214]}};

assign trunc_ln44_215_fu_2295_p4 = {{layer2_out_dout[2249:2232]}};

assign trunc_ln44_216_fu_2305_p4 = {{layer2_out_dout[2267:2250]}};

assign trunc_ln44_217_fu_2315_p4 = {{layer2_out_dout[2285:2268]}};

assign trunc_ln44_218_fu_2325_p4 = {{layer2_out_dout[2303:2286]}};

assign trunc_ln44_93_fu_1075_p4 = {{layer2_out_dout[53:36]}};

assign trunc_ln44_94_fu_1085_p4 = {{layer2_out_dout[71:54]}};

assign trunc_ln44_95_fu_1095_p4 = {{layer2_out_dout[89:72]}};

assign trunc_ln44_96_fu_1105_p4 = {{layer2_out_dout[107:90]}};

assign trunc_ln44_97_fu_1115_p4 = {{layer2_out_dout[125:108]}};

assign trunc_ln44_98_fu_1125_p4 = {{layer2_out_dout[143:126]}};

assign trunc_ln44_99_fu_1135_p4 = {{layer2_out_dout[161:144]}};

assign trunc_ln44_fu_1061_p1 = layer2_out_dout[17:0];

assign trunc_ln44_s_fu_1065_p4 = {{layer2_out_dout[35:18]}};

assign trunc_ln4_fu_2341_p4 = {{layer2_out_dout[15:8]}};

assign trunc_ln52_100_fu_2557_p4 = {{layer2_out_dout[177:170]}};

assign trunc_ln52_101_fu_2581_p4 = {{layer2_out_dout[195:188]}};

assign trunc_ln52_102_fu_2605_p4 = {{layer2_out_dout[213:206]}};

assign trunc_ln52_103_fu_2629_p4 = {{layer2_out_dout[231:224]}};

assign trunc_ln52_104_fu_2653_p4 = {{layer2_out_dout[249:242]}};

assign trunc_ln52_105_fu_2677_p4 = {{layer2_out_dout[267:260]}};

assign trunc_ln52_106_fu_2701_p4 = {{layer2_out_dout[285:278]}};

assign trunc_ln52_107_fu_2725_p4 = {{layer2_out_dout[303:296]}};

assign trunc_ln52_108_fu_2749_p4 = {{layer2_out_dout[321:314]}};

assign trunc_ln52_109_fu_2773_p4 = {{layer2_out_dout[339:332]}};

assign trunc_ln52_110_fu_2797_p4 = {{layer2_out_dout[357:350]}};

assign trunc_ln52_111_fu_2821_p4 = {{layer2_out_dout[375:368]}};

assign trunc_ln52_112_fu_2845_p4 = {{layer2_out_dout[393:386]}};

assign trunc_ln52_113_fu_2869_p4 = {{layer2_out_dout[411:404]}};

assign trunc_ln52_114_fu_2893_p4 = {{layer2_out_dout[429:422]}};

assign trunc_ln52_115_fu_2917_p4 = {{layer2_out_dout[447:440]}};

assign trunc_ln52_116_fu_2941_p4 = {{layer2_out_dout[465:458]}};

assign trunc_ln52_117_fu_2965_p4 = {{layer2_out_dout[483:476]}};

assign trunc_ln52_118_fu_2989_p4 = {{layer2_out_dout[501:494]}};

assign trunc_ln52_119_fu_3013_p4 = {{layer2_out_dout[519:512]}};

assign trunc_ln52_120_fu_3037_p4 = {{layer2_out_dout[537:530]}};

assign trunc_ln52_121_fu_3061_p4 = {{layer2_out_dout[555:548]}};

assign trunc_ln52_122_fu_3085_p4 = {{layer2_out_dout[573:566]}};

assign trunc_ln52_123_fu_3109_p4 = {{layer2_out_dout[591:584]}};

assign trunc_ln52_124_fu_3133_p4 = {{layer2_out_dout[609:602]}};

assign trunc_ln52_125_fu_3157_p4 = {{layer2_out_dout[627:620]}};

assign trunc_ln52_126_fu_3181_p4 = {{layer2_out_dout[645:638]}};

assign trunc_ln52_127_fu_3205_p4 = {{layer2_out_dout[663:656]}};

assign trunc_ln52_128_fu_3229_p4 = {{layer2_out_dout[681:674]}};

assign trunc_ln52_129_fu_3253_p4 = {{layer2_out_dout[699:692]}};

assign trunc_ln52_130_fu_3277_p4 = {{layer2_out_dout[717:710]}};

assign trunc_ln52_131_fu_3301_p4 = {{layer2_out_dout[735:728]}};

assign trunc_ln52_132_fu_3325_p4 = {{layer2_out_dout[753:746]}};

assign trunc_ln52_133_fu_3349_p4 = {{layer2_out_dout[771:764]}};

assign trunc_ln52_134_fu_3373_p4 = {{layer2_out_dout[789:782]}};

assign trunc_ln52_135_fu_3397_p4 = {{layer2_out_dout[807:800]}};

assign trunc_ln52_136_fu_3421_p4 = {{layer2_out_dout[825:818]}};

assign trunc_ln52_137_fu_3445_p4 = {{layer2_out_dout[843:836]}};

assign trunc_ln52_138_fu_3469_p4 = {{layer2_out_dout[861:854]}};

assign trunc_ln52_139_fu_3493_p4 = {{layer2_out_dout[879:872]}};

assign trunc_ln52_140_fu_3517_p4 = {{layer2_out_dout[897:890]}};

assign trunc_ln52_141_fu_3541_p4 = {{layer2_out_dout[915:908]}};

assign trunc_ln52_142_fu_3565_p4 = {{layer2_out_dout[933:926]}};

assign trunc_ln52_143_fu_3589_p4 = {{layer2_out_dout[951:944]}};

assign trunc_ln52_144_fu_3613_p4 = {{layer2_out_dout[969:962]}};

assign trunc_ln52_145_fu_3637_p4 = {{layer2_out_dout[987:980]}};

assign trunc_ln52_146_fu_3661_p4 = {{layer2_out_dout[1005:998]}};

assign trunc_ln52_147_fu_3685_p4 = {{layer2_out_dout[1023:1016]}};

assign trunc_ln52_148_fu_3709_p4 = {{layer2_out_dout[1041:1034]}};

assign trunc_ln52_149_fu_3733_p4 = {{layer2_out_dout[1059:1052]}};

assign trunc_ln52_150_fu_3757_p4 = {{layer2_out_dout[1077:1070]}};

assign trunc_ln52_151_fu_3781_p4 = {{layer2_out_dout[1095:1088]}};

assign trunc_ln52_152_fu_3805_p4 = {{layer2_out_dout[1113:1106]}};

assign trunc_ln52_153_fu_3829_p4 = {{layer2_out_dout[1131:1124]}};

assign trunc_ln52_154_fu_3853_p4 = {{layer2_out_dout[1149:1142]}};

assign trunc_ln52_155_fu_3877_p4 = {{layer2_out_dout[1167:1160]}};

assign trunc_ln52_156_fu_3901_p4 = {{layer2_out_dout[1185:1178]}};

assign trunc_ln52_157_fu_3925_p4 = {{layer2_out_dout[1203:1196]}};

assign trunc_ln52_158_fu_3949_p4 = {{layer2_out_dout[1221:1214]}};

assign trunc_ln52_159_fu_3973_p4 = {{layer2_out_dout[1239:1232]}};

assign trunc_ln52_160_fu_3997_p4 = {{layer2_out_dout[1257:1250]}};

assign trunc_ln52_161_fu_4021_p4 = {{layer2_out_dout[1275:1268]}};

assign trunc_ln52_162_fu_4045_p4 = {{layer2_out_dout[1293:1286]}};

assign trunc_ln52_163_fu_4069_p4 = {{layer2_out_dout[1311:1304]}};

assign trunc_ln52_164_fu_4093_p4 = {{layer2_out_dout[1329:1322]}};

assign trunc_ln52_165_fu_4117_p4 = {{layer2_out_dout[1347:1340]}};

assign trunc_ln52_166_fu_4141_p4 = {{layer2_out_dout[1365:1358]}};

assign trunc_ln52_167_fu_4165_p4 = {{layer2_out_dout[1383:1376]}};

assign trunc_ln52_168_fu_4189_p4 = {{layer2_out_dout[1401:1394]}};

assign trunc_ln52_169_fu_4213_p4 = {{layer2_out_dout[1419:1412]}};

assign trunc_ln52_170_fu_4237_p4 = {{layer2_out_dout[1437:1430]}};

assign trunc_ln52_171_fu_4261_p4 = {{layer2_out_dout[1455:1448]}};

assign trunc_ln52_172_fu_4285_p4 = {{layer2_out_dout[1473:1466]}};

assign trunc_ln52_173_fu_4309_p4 = {{layer2_out_dout[1491:1484]}};

assign trunc_ln52_174_fu_4333_p4 = {{layer2_out_dout[1509:1502]}};

assign trunc_ln52_175_fu_4357_p4 = {{layer2_out_dout[1527:1520]}};

assign trunc_ln52_176_fu_4381_p4 = {{layer2_out_dout[1545:1538]}};

assign trunc_ln52_177_fu_4405_p4 = {{layer2_out_dout[1563:1556]}};

assign trunc_ln52_178_fu_4429_p4 = {{layer2_out_dout[1581:1574]}};

assign trunc_ln52_179_fu_4453_p4 = {{layer2_out_dout[1599:1592]}};

assign trunc_ln52_180_fu_4477_p4 = {{layer2_out_dout[1617:1610]}};

assign trunc_ln52_181_fu_4501_p4 = {{layer2_out_dout[1635:1628]}};

assign trunc_ln52_182_fu_4525_p4 = {{layer2_out_dout[1653:1646]}};

assign trunc_ln52_183_fu_4549_p4 = {{layer2_out_dout[1671:1664]}};

assign trunc_ln52_184_fu_4573_p4 = {{layer2_out_dout[1689:1682]}};

assign trunc_ln52_185_fu_4597_p4 = {{layer2_out_dout[1707:1700]}};

assign trunc_ln52_186_fu_4621_p4 = {{layer2_out_dout[1725:1718]}};

assign trunc_ln52_187_fu_4645_p4 = {{layer2_out_dout[1743:1736]}};

assign trunc_ln52_188_fu_4669_p4 = {{layer2_out_dout[1761:1754]}};

assign trunc_ln52_189_fu_4693_p4 = {{layer2_out_dout[1779:1772]}};

assign trunc_ln52_190_fu_4717_p4 = {{layer2_out_dout[1797:1790]}};

assign trunc_ln52_191_fu_4741_p4 = {{layer2_out_dout[1815:1808]}};

assign trunc_ln52_192_fu_4765_p4 = {{layer2_out_dout[1833:1826]}};

assign trunc_ln52_193_fu_4789_p4 = {{layer2_out_dout[1851:1844]}};

assign trunc_ln52_194_fu_4813_p4 = {{layer2_out_dout[1869:1862]}};

assign trunc_ln52_195_fu_4837_p4 = {{layer2_out_dout[1887:1880]}};

assign trunc_ln52_196_fu_4861_p4 = {{layer2_out_dout[1905:1898]}};

assign trunc_ln52_197_fu_4885_p4 = {{layer2_out_dout[1923:1916]}};

assign trunc_ln52_198_fu_4909_p4 = {{layer2_out_dout[1941:1934]}};

assign trunc_ln52_199_fu_4933_p4 = {{layer2_out_dout[1959:1952]}};

assign trunc_ln52_200_fu_4957_p4 = {{layer2_out_dout[1977:1970]}};

assign trunc_ln52_201_fu_4981_p4 = {{layer2_out_dout[1995:1988]}};

assign trunc_ln52_202_fu_5005_p4 = {{layer2_out_dout[2013:2006]}};

assign trunc_ln52_203_fu_5029_p4 = {{layer2_out_dout[2031:2024]}};

assign trunc_ln52_204_fu_5053_p4 = {{layer2_out_dout[2049:2042]}};

assign trunc_ln52_205_fu_5077_p4 = {{layer2_out_dout[2067:2060]}};

assign trunc_ln52_206_fu_5101_p4 = {{layer2_out_dout[2085:2078]}};

assign trunc_ln52_207_fu_5125_p4 = {{layer2_out_dout[2103:2096]}};

assign trunc_ln52_208_fu_5149_p4 = {{layer2_out_dout[2121:2114]}};

assign trunc_ln52_209_fu_5173_p4 = {{layer2_out_dout[2139:2132]}};

assign trunc_ln52_210_fu_5197_p4 = {{layer2_out_dout[2157:2150]}};

assign trunc_ln52_211_fu_5221_p4 = {{layer2_out_dout[2175:2168]}};

assign trunc_ln52_212_fu_5245_p4 = {{layer2_out_dout[2193:2186]}};

assign trunc_ln52_213_fu_5269_p4 = {{layer2_out_dout[2211:2204]}};

assign trunc_ln52_214_fu_5293_p4 = {{layer2_out_dout[2229:2222]}};

assign trunc_ln52_215_fu_5317_p4 = {{layer2_out_dout[2247:2240]}};

assign trunc_ln52_216_fu_5341_p4 = {{layer2_out_dout[2265:2258]}};

assign trunc_ln52_217_fu_5365_p4 = {{layer2_out_dout[2283:2276]}};

assign trunc_ln52_218_fu_5389_p4 = {{layer2_out_dout[2301:2294]}};

assign trunc_ln52_93_fu_2389_p4 = {{layer2_out_dout[51:44]}};

assign trunc_ln52_94_fu_2413_p4 = {{layer2_out_dout[69:62]}};

assign trunc_ln52_95_fu_2437_p4 = {{layer2_out_dout[87:80]}};

assign trunc_ln52_96_fu_2461_p4 = {{layer2_out_dout[105:98]}};

assign trunc_ln52_97_fu_2485_p4 = {{layer2_out_dout[123:116]}};

assign trunc_ln52_98_fu_2509_p4 = {{layer2_out_dout[141:134]}};

assign trunc_ln52_99_fu_2533_p4 = {{layer2_out_dout[159:152]}};

assign trunc_ln52_s_fu_2365_p4 = {{layer2_out_dout[33:26]}};

endmodule //myproject_relu_array_ap_fixed_128u_array_ap_fixed_8_4_5_3_0_128u_relu_config3_s
