// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_128u_array_ap_fixed_18_6_5_3_0_64u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
output  [1151:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer3_out_read;
reg layer4_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [7:0] data_fu_1007_p1;
reg   [7:0] data_reg_3118;
reg    ap_block_state1;
reg   [7:0] data_249_reg_3123;
reg   [7:0] data_123_reg_3128;
reg   [7:0] data_124_reg_3133;
reg   [7:0] data_125_reg_3138;
reg   [7:0] data_126_reg_3143;
reg   [7:0] data_127_reg_3148;
reg   [7:0] data_128_reg_3153;
reg   [7:0] data_129_reg_3158;
reg   [7:0] data_130_reg_3163;
reg   [7:0] data_131_reg_3168;
reg   [7:0] data_132_reg_3173;
reg   [7:0] data_133_reg_3178;
reg   [7:0] data_134_reg_3183;
reg   [7:0] data_135_reg_3188;
reg   [7:0] data_136_reg_3193;
reg   [7:0] data_137_reg_3198;
reg   [7:0] data_138_reg_3203;
reg   [7:0] data_139_reg_3208;
reg   [7:0] data_140_reg_3213;
reg   [7:0] data_141_reg_3218;
reg   [7:0] data_142_reg_3223;
reg   [7:0] data_143_reg_3228;
reg   [7:0] data_144_reg_3233;
reg   [7:0] data_145_reg_3238;
reg   [7:0] data_146_reg_3243;
reg   [7:0] data_147_reg_3248;
reg   [7:0] data_148_reg_3253;
reg   [7:0] data_149_reg_3258;
reg   [7:0] data_150_reg_3263;
reg   [7:0] data_151_reg_3268;
reg   [7:0] data_152_reg_3273;
reg   [7:0] data_153_reg_3278;
reg   [7:0] data_154_reg_3283;
reg   [7:0] data_155_reg_3288;
reg   [7:0] data_156_reg_3293;
reg   [7:0] data_157_reg_3298;
reg   [7:0] data_158_reg_3303;
reg   [7:0] data_159_reg_3308;
reg   [7:0] data_160_reg_3313;
reg   [7:0] data_161_reg_3318;
reg   [7:0] data_162_reg_3323;
reg   [7:0] data_163_reg_3328;
reg   [7:0] data_164_reg_3333;
reg   [7:0] data_165_reg_3338;
reg   [7:0] data_166_reg_3343;
reg   [7:0] data_167_reg_3348;
reg   [7:0] data_168_reg_3353;
reg   [7:0] data_169_reg_3358;
reg   [7:0] data_170_reg_3363;
reg   [7:0] data_171_reg_3368;
reg   [7:0] data_172_reg_3373;
reg   [7:0] data_173_reg_3378;
reg   [7:0] data_174_reg_3383;
reg   [7:0] data_175_reg_3388;
reg   [7:0] data_176_reg_3393;
reg   [7:0] data_177_reg_3398;
reg   [7:0] data_178_reg_3403;
reg   [7:0] data_179_reg_3408;
reg   [7:0] data_180_reg_3413;
reg   [7:0] data_181_reg_3418;
reg   [7:0] data_182_reg_3423;
reg   [7:0] data_183_reg_3428;
reg   [7:0] data_184_reg_3433;
reg   [7:0] data_185_reg_3438;
reg   [7:0] data_186_reg_3443;
reg   [7:0] data_187_reg_3448;
reg   [7:0] data_188_reg_3453;
reg   [7:0] data_189_reg_3458;
reg   [7:0] data_190_reg_3463;
reg   [7:0] data_191_reg_3468;
reg   [7:0] data_192_reg_3473;
reg   [7:0] data_193_reg_3478;
reg   [7:0] data_194_reg_3483;
reg   [7:0] data_195_reg_3488;
reg   [7:0] data_196_reg_3493;
reg   [7:0] data_197_reg_3498;
reg   [7:0] data_198_reg_3503;
reg   [7:0] data_199_reg_3508;
reg   [7:0] data_200_reg_3513;
reg   [7:0] data_201_reg_3518;
reg   [7:0] data_202_reg_3523;
reg   [7:0] data_203_reg_3528;
reg   [7:0] data_204_reg_3533;
reg   [7:0] data_205_reg_3538;
reg   [7:0] data_206_reg_3543;
reg   [7:0] data_207_reg_3548;
reg   [7:0] data_208_reg_3553;
reg   [7:0] data_209_reg_3558;
reg   [7:0] data_210_reg_3563;
reg   [7:0] data_211_reg_3568;
reg   [7:0] data_212_reg_3573;
reg   [7:0] data_213_reg_3578;
reg   [7:0] data_214_reg_3583;
reg   [7:0] data_215_reg_3588;
reg   [7:0] data_216_reg_3593;
reg   [7:0] data_217_reg_3598;
reg   [7:0] data_218_reg_3603;
reg   [7:0] data_219_reg_3608;
reg   [7:0] data_220_reg_3613;
reg   [7:0] data_221_reg_3618;
reg   [7:0] data_222_reg_3623;
reg   [7:0] data_223_reg_3628;
reg   [7:0] data_224_reg_3633;
reg   [7:0] data_225_reg_3638;
reg   [7:0] data_226_reg_3643;
reg   [7:0] data_227_reg_3648;
reg   [7:0] data_228_reg_3653;
reg   [7:0] data_229_reg_3658;
reg   [7:0] data_230_reg_3663;
reg   [7:0] data_231_reg_3668;
reg   [7:0] data_232_reg_3673;
reg   [7:0] data_233_reg_3678;
reg   [7:0] data_234_reg_3683;
reg   [7:0] data_235_reg_3688;
reg   [7:0] data_236_reg_3693;
reg   [7:0] data_237_reg_3698;
reg   [7:0] data_238_reg_3703;
reg   [7:0] data_239_reg_3708;
reg   [7:0] data_240_reg_3713;
reg   [7:0] data_241_reg_3718;
reg   [7:0] data_242_reg_3723;
reg   [7:0] data_243_reg_3728;
reg   [7:0] data_244_reg_3733;
reg   [7:0] data_245_reg_3738;
reg   [7:0] data_246_reg_3743;
reg   [7:0] data_247_reg_3748;
reg   [7:0] data_248_reg_3753;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_done;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_idle;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_ready;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62_ap_vld;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63_ap_vld;
reg    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg;
reg    ap_block_state1_ignore_call195;
wire    ap_CS_fsm_state2;
reg   [17:0] res_fu_538;
reg   [17:0] res_1_fu_542;
reg   [17:0] res_2_fu_546;
reg   [17:0] res_3_fu_550;
reg   [17:0] res_4_fu_554;
reg   [17:0] res_5_fu_558;
reg   [17:0] res_6_fu_562;
reg   [17:0] res_7_fu_566;
reg   [17:0] res_8_fu_570;
reg   [17:0] res_9_fu_574;
reg   [17:0] res_10_fu_578;
reg   [17:0] res_11_fu_582;
reg   [17:0] res_12_fu_586;
reg   [17:0] res_13_fu_590;
reg   [17:0] res_14_fu_594;
reg   [17:0] res_15_fu_598;
reg   [17:0] res_16_fu_602;
reg   [17:0] res_17_fu_606;
reg   [17:0] res_18_fu_610;
reg   [17:0] res_19_fu_614;
reg   [17:0] res_20_fu_618;
reg   [17:0] res_21_fu_622;
reg   [17:0] res_22_fu_626;
reg   [17:0] res_23_fu_630;
reg   [17:0] res_24_fu_634;
reg   [17:0] res_25_fu_638;
reg   [17:0] res_26_fu_642;
reg   [17:0] res_27_fu_646;
reg   [17:0] res_28_fu_650;
reg   [17:0] res_29_fu_654;
reg   [17:0] res_30_fu_658;
reg   [17:0] res_31_fu_662;
reg   [17:0] res_32_fu_666;
reg   [17:0] res_33_fu_670;
reg   [17:0] res_34_fu_674;
reg   [17:0] res_35_fu_678;
reg   [17:0] res_36_fu_682;
reg   [17:0] res_37_fu_686;
reg   [17:0] res_38_fu_690;
reg   [17:0] res_39_fu_694;
reg   [17:0] res_40_fu_698;
reg   [17:0] res_41_fu_702;
reg   [17:0] res_42_fu_706;
reg   [17:0] res_43_fu_710;
reg   [17:0] res_44_fu_714;
reg   [17:0] res_45_fu_718;
reg   [17:0] res_46_fu_722;
reg   [17:0] res_47_fu_726;
reg   [17:0] res_48_fu_730;
reg   [17:0] res_49_fu_734;
reg   [17:0] res_50_fu_738;
reg   [17:0] res_51_fu_742;
reg   [17:0] res_52_fu_746;
reg   [17:0] res_53_fu_750;
reg   [17:0] res_54_fu_754;
reg   [17:0] res_55_fu_758;
reg   [17:0] res_56_fu_762;
reg   [17:0] res_57_fu_766;
reg   [17:0] res_58_fu_770;
reg   [17:0] res_59_fu_774;
reg   [17:0] res_60_fu_778;
reg   [17:0] res_61_fu_782;
reg   [17:0] res_62_fu_786;
reg   [17:0] res_63_fu_790;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg = 1'b0;
end

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start),
    .ap_done(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_done),
    .ap_idle(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_idle),
    .ap_ready(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_ready),
    .data_0_val(data_reg_3118),
    .data_1_val(data_249_reg_3123),
    .data_2_val(data_123_reg_3128),
    .data_3_val(data_124_reg_3133),
    .data_4_val(data_125_reg_3138),
    .data_5_val(data_126_reg_3143),
    .data_6_val(data_127_reg_3148),
    .data_7_val(data_128_reg_3153),
    .data_8_val(data_129_reg_3158),
    .data_9_val(data_130_reg_3163),
    .data_10_val(data_131_reg_3168),
    .data_11_val(data_132_reg_3173),
    .data_12_val(data_133_reg_3178),
    .data_13_val(data_134_reg_3183),
    .data_14_val(data_135_reg_3188),
    .data_15_val(data_136_reg_3193),
    .data_16_val(data_137_reg_3198),
    .data_17_val(data_138_reg_3203),
    .data_18_val(data_139_reg_3208),
    .data_19_val(data_140_reg_3213),
    .data_20_val(data_141_reg_3218),
    .data_21_val(data_142_reg_3223),
    .data_22_val(data_143_reg_3228),
    .data_23_val(data_144_reg_3233),
    .data_24_val(data_145_reg_3238),
    .data_25_val(data_146_reg_3243),
    .data_26_val(data_147_reg_3248),
    .data_27_val(data_148_reg_3253),
    .data_28_val(data_149_reg_3258),
    .data_29_val(data_150_reg_3263),
    .data_30_val(data_151_reg_3268),
    .data_31_val(data_152_reg_3273),
    .data_32_val(data_153_reg_3278),
    .data_33_val(data_154_reg_3283),
    .data_34_val(data_155_reg_3288),
    .data_35_val(data_156_reg_3293),
    .data_36_val(data_157_reg_3298),
    .data_37_val(data_158_reg_3303),
    .data_38_val(data_159_reg_3308),
    .data_39_val(data_160_reg_3313),
    .data_40_val(data_161_reg_3318),
    .data_41_val(data_162_reg_3323),
    .data_42_val(data_163_reg_3328),
    .data_43_val(data_164_reg_3333),
    .data_44_val(data_165_reg_3338),
    .data_45_val(data_166_reg_3343),
    .data_46_val(data_167_reg_3348),
    .data_47_val(data_168_reg_3353),
    .data_48_val(data_169_reg_3358),
    .data_49_val(data_170_reg_3363),
    .data_50_val(data_171_reg_3368),
    .data_51_val(data_172_reg_3373),
    .data_52_val(data_173_reg_3378),
    .data_53_val(data_174_reg_3383),
    .data_54_val(data_175_reg_3388),
    .data_55_val(data_176_reg_3393),
    .data_56_val(data_177_reg_3398),
    .data_57_val(data_178_reg_3403),
    .data_58_val(data_179_reg_3408),
    .data_59_val(data_180_reg_3413),
    .data_60_val(data_181_reg_3418),
    .data_61_val(data_182_reg_3423),
    .data_62_val(data_183_reg_3428),
    .data_63_val(data_184_reg_3433),
    .data_64_val(data_185_reg_3438),
    .data_65_val(data_186_reg_3443),
    .data_66_val(data_187_reg_3448),
    .data_67_val(data_188_reg_3453),
    .data_68_val(data_189_reg_3458),
    .data_69_val(data_190_reg_3463),
    .data_70_val(data_191_reg_3468),
    .data_71_val(data_192_reg_3473),
    .data_72_val(data_193_reg_3478),
    .data_73_val(data_194_reg_3483),
    .data_74_val(data_195_reg_3488),
    .data_75_val(data_196_reg_3493),
    .data_76_val(data_197_reg_3498),
    .data_77_val(data_198_reg_3503),
    .data_78_val(data_199_reg_3508),
    .data_79_val(data_200_reg_3513),
    .data_80_val(data_201_reg_3518),
    .data_81_val(data_202_reg_3523),
    .data_82_val(data_203_reg_3528),
    .data_83_val(data_204_reg_3533),
    .data_84_val(data_205_reg_3538),
    .data_85_val(data_206_reg_3543),
    .data_86_val(data_207_reg_3548),
    .data_87_val(data_208_reg_3553),
    .data_88_val(data_209_reg_3558),
    .data_89_val(data_210_reg_3563),
    .data_90_val(data_211_reg_3568),
    .data_91_val(data_212_reg_3573),
    .data_92_val(data_213_reg_3578),
    .data_93_val(data_214_reg_3583),
    .data_94_val(data_215_reg_3588),
    .data_95_val(data_216_reg_3593),
    .data_96_val(data_217_reg_3598),
    .data_97_val(data_218_reg_3603),
    .data_98_val(data_219_reg_3608),
    .data_99_val(data_220_reg_3613),
    .data_100_val(data_221_reg_3618),
    .data_101_val(data_222_reg_3623),
    .data_102_val(data_223_reg_3628),
    .data_103_val(data_224_reg_3633),
    .data_104_val(data_225_reg_3638),
    .data_105_val(data_226_reg_3643),
    .data_106_val(data_227_reg_3648),
    .data_107_val(data_228_reg_3653),
    .data_108_val(data_229_reg_3658),
    .data_109_val(data_230_reg_3663),
    .data_110_val(data_231_reg_3668),
    .data_111_val(data_232_reg_3673),
    .data_112_val(data_233_reg_3678),
    .data_113_val(data_234_reg_3683),
    .data_114_val(data_235_reg_3688),
    .data_115_val(data_236_reg_3693),
    .data_116_val(data_237_reg_3698),
    .data_117_val(data_238_reg_3703),
    .data_118_val(data_239_reg_3708),
    .data_119_val(data_240_reg_3713),
    .data_120_val(data_241_reg_3718),
    .data_121_val(data_242_reg_3723),
    .data_122_val(data_243_reg_3728),
    .data_123_val(data_244_reg_3733),
    .data_124_val(data_245_reg_3738),
    .data_125_val(data_246_reg_3743),
    .data_126_val(data_247_reg_3748),
    .data_127_val(data_248_reg_3753),
    .res_0(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0),
    .res_0_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0_ap_vld),
    .res_1(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1),
    .res_1_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1_ap_vld),
    .res_2(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2),
    .res_2_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2_ap_vld),
    .res_3(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3),
    .res_3_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3_ap_vld),
    .res_4(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4),
    .res_4_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4_ap_vld),
    .res_5(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5),
    .res_5_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5_ap_vld),
    .res_6(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6),
    .res_6_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6_ap_vld),
    .res_7(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7),
    .res_7_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7_ap_vld),
    .res_8(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8),
    .res_8_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8_ap_vld),
    .res_9(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9),
    .res_9_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9_ap_vld),
    .res_10(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10),
    .res_10_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10_ap_vld),
    .res_11(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11),
    .res_11_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11_ap_vld),
    .res_12(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12),
    .res_12_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12_ap_vld),
    .res_13(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13),
    .res_13_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13_ap_vld),
    .res_14(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14),
    .res_14_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14_ap_vld),
    .res_15(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15),
    .res_15_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15_ap_vld),
    .res_16(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16),
    .res_16_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16_ap_vld),
    .res_17(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17),
    .res_17_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17_ap_vld),
    .res_18(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18),
    .res_18_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18_ap_vld),
    .res_19(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19),
    .res_19_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19_ap_vld),
    .res_20(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20),
    .res_20_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20_ap_vld),
    .res_21(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21),
    .res_21_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21_ap_vld),
    .res_22(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22),
    .res_22_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22_ap_vld),
    .res_23(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23),
    .res_23_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23_ap_vld),
    .res_24(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24),
    .res_24_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24_ap_vld),
    .res_25(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25),
    .res_25_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25_ap_vld),
    .res_26(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26),
    .res_26_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26_ap_vld),
    .res_27(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27),
    .res_27_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27_ap_vld),
    .res_28(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28),
    .res_28_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28_ap_vld),
    .res_29(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29),
    .res_29_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29_ap_vld),
    .res_30(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30),
    .res_30_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30_ap_vld),
    .res_31(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31),
    .res_31_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31_ap_vld),
    .res_32(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32),
    .res_32_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32_ap_vld),
    .res_33(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33),
    .res_33_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33_ap_vld),
    .res_34(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34),
    .res_34_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34_ap_vld),
    .res_35(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35),
    .res_35_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35_ap_vld),
    .res_36(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36),
    .res_36_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36_ap_vld),
    .res_37(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37),
    .res_37_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37_ap_vld),
    .res_38(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38),
    .res_38_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38_ap_vld),
    .res_39(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39),
    .res_39_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39_ap_vld),
    .res_40(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40),
    .res_40_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40_ap_vld),
    .res_41(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41),
    .res_41_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41_ap_vld),
    .res_42(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42),
    .res_42_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42_ap_vld),
    .res_43(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43),
    .res_43_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43_ap_vld),
    .res_44(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44),
    .res_44_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44_ap_vld),
    .res_45(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45),
    .res_45_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45_ap_vld),
    .res_46(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46),
    .res_46_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46_ap_vld),
    .res_47(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47),
    .res_47_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47_ap_vld),
    .res_48(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48),
    .res_48_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48_ap_vld),
    .res_49(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49),
    .res_49_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49_ap_vld),
    .res_50(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50),
    .res_50_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50_ap_vld),
    .res_51(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51),
    .res_51_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51_ap_vld),
    .res_52(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52),
    .res_52_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52_ap_vld),
    .res_53(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53),
    .res_53_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53_ap_vld),
    .res_54(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54),
    .res_54_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54_ap_vld),
    .res_55(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55),
    .res_55_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55_ap_vld),
    .res_56(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56),
    .res_56_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56_ap_vld),
    .res_57(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57),
    .res_57_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57_ap_vld),
    .res_58(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58),
    .res_58_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58_ap_vld),
    .res_59(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59),
    .res_59_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59_ap_vld),
    .res_60(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60),
    .res_60_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60_ap_vld),
    .res_61(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61),
    .res_61_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61_ap_vld),
    .res_62(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62),
    .res_62_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62_ap_vld),
    .res_63(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63),
    .res_63_ap_vld(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call195) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_123_reg_3128 <= {{layer3_out_dout[23:16]}};
        data_124_reg_3133 <= {{layer3_out_dout[31:24]}};
        data_125_reg_3138 <= {{layer3_out_dout[39:32]}};
        data_126_reg_3143 <= {{layer3_out_dout[47:40]}};
        data_127_reg_3148 <= {{layer3_out_dout[55:48]}};
        data_128_reg_3153 <= {{layer3_out_dout[63:56]}};
        data_129_reg_3158 <= {{layer3_out_dout[71:64]}};
        data_130_reg_3163 <= {{layer3_out_dout[79:72]}};
        data_131_reg_3168 <= {{layer3_out_dout[87:80]}};
        data_132_reg_3173 <= {{layer3_out_dout[95:88]}};
        data_133_reg_3178 <= {{layer3_out_dout[103:96]}};
        data_134_reg_3183 <= {{layer3_out_dout[111:104]}};
        data_135_reg_3188 <= {{layer3_out_dout[119:112]}};
        data_136_reg_3193 <= {{layer3_out_dout[127:120]}};
        data_137_reg_3198 <= {{layer3_out_dout[135:128]}};
        data_138_reg_3203 <= {{layer3_out_dout[143:136]}};
        data_139_reg_3208 <= {{layer3_out_dout[151:144]}};
        data_140_reg_3213 <= {{layer3_out_dout[159:152]}};
        data_141_reg_3218 <= {{layer3_out_dout[167:160]}};
        data_142_reg_3223 <= {{layer3_out_dout[175:168]}};
        data_143_reg_3228 <= {{layer3_out_dout[183:176]}};
        data_144_reg_3233 <= {{layer3_out_dout[191:184]}};
        data_145_reg_3238 <= {{layer3_out_dout[199:192]}};
        data_146_reg_3243 <= {{layer3_out_dout[207:200]}};
        data_147_reg_3248 <= {{layer3_out_dout[215:208]}};
        data_148_reg_3253 <= {{layer3_out_dout[223:216]}};
        data_149_reg_3258 <= {{layer3_out_dout[231:224]}};
        data_150_reg_3263 <= {{layer3_out_dout[239:232]}};
        data_151_reg_3268 <= {{layer3_out_dout[247:240]}};
        data_152_reg_3273 <= {{layer3_out_dout[255:248]}};
        data_153_reg_3278 <= {{layer3_out_dout[263:256]}};
        data_154_reg_3283 <= {{layer3_out_dout[271:264]}};
        data_155_reg_3288 <= {{layer3_out_dout[279:272]}};
        data_156_reg_3293 <= {{layer3_out_dout[287:280]}};
        data_157_reg_3298 <= {{layer3_out_dout[295:288]}};
        data_158_reg_3303 <= {{layer3_out_dout[303:296]}};
        data_159_reg_3308 <= {{layer3_out_dout[311:304]}};
        data_160_reg_3313 <= {{layer3_out_dout[319:312]}};
        data_161_reg_3318 <= {{layer3_out_dout[327:320]}};
        data_162_reg_3323 <= {{layer3_out_dout[335:328]}};
        data_163_reg_3328 <= {{layer3_out_dout[343:336]}};
        data_164_reg_3333 <= {{layer3_out_dout[351:344]}};
        data_165_reg_3338 <= {{layer3_out_dout[359:352]}};
        data_166_reg_3343 <= {{layer3_out_dout[367:360]}};
        data_167_reg_3348 <= {{layer3_out_dout[375:368]}};
        data_168_reg_3353 <= {{layer3_out_dout[383:376]}};
        data_169_reg_3358 <= {{layer3_out_dout[391:384]}};
        data_170_reg_3363 <= {{layer3_out_dout[399:392]}};
        data_171_reg_3368 <= {{layer3_out_dout[407:400]}};
        data_172_reg_3373 <= {{layer3_out_dout[415:408]}};
        data_173_reg_3378 <= {{layer3_out_dout[423:416]}};
        data_174_reg_3383 <= {{layer3_out_dout[431:424]}};
        data_175_reg_3388 <= {{layer3_out_dout[439:432]}};
        data_176_reg_3393 <= {{layer3_out_dout[447:440]}};
        data_177_reg_3398 <= {{layer3_out_dout[455:448]}};
        data_178_reg_3403 <= {{layer3_out_dout[463:456]}};
        data_179_reg_3408 <= {{layer3_out_dout[471:464]}};
        data_180_reg_3413 <= {{layer3_out_dout[479:472]}};
        data_181_reg_3418 <= {{layer3_out_dout[487:480]}};
        data_182_reg_3423 <= {{layer3_out_dout[495:488]}};
        data_183_reg_3428 <= {{layer3_out_dout[503:496]}};
        data_184_reg_3433 <= {{layer3_out_dout[511:504]}};
        data_185_reg_3438 <= {{layer3_out_dout[519:512]}};
        data_186_reg_3443 <= {{layer3_out_dout[527:520]}};
        data_187_reg_3448 <= {{layer3_out_dout[535:528]}};
        data_188_reg_3453 <= {{layer3_out_dout[543:536]}};
        data_189_reg_3458 <= {{layer3_out_dout[551:544]}};
        data_190_reg_3463 <= {{layer3_out_dout[559:552]}};
        data_191_reg_3468 <= {{layer3_out_dout[567:560]}};
        data_192_reg_3473 <= {{layer3_out_dout[575:568]}};
        data_193_reg_3478 <= {{layer3_out_dout[583:576]}};
        data_194_reg_3483 <= {{layer3_out_dout[591:584]}};
        data_195_reg_3488 <= {{layer3_out_dout[599:592]}};
        data_196_reg_3493 <= {{layer3_out_dout[607:600]}};
        data_197_reg_3498 <= {{layer3_out_dout[615:608]}};
        data_198_reg_3503 <= {{layer3_out_dout[623:616]}};
        data_199_reg_3508 <= {{layer3_out_dout[631:624]}};
        data_200_reg_3513 <= {{layer3_out_dout[639:632]}};
        data_201_reg_3518 <= {{layer3_out_dout[647:640]}};
        data_202_reg_3523 <= {{layer3_out_dout[655:648]}};
        data_203_reg_3528 <= {{layer3_out_dout[663:656]}};
        data_204_reg_3533 <= {{layer3_out_dout[671:664]}};
        data_205_reg_3538 <= {{layer3_out_dout[679:672]}};
        data_206_reg_3543 <= {{layer3_out_dout[687:680]}};
        data_207_reg_3548 <= {{layer3_out_dout[695:688]}};
        data_208_reg_3553 <= {{layer3_out_dout[703:696]}};
        data_209_reg_3558 <= {{layer3_out_dout[711:704]}};
        data_210_reg_3563 <= {{layer3_out_dout[719:712]}};
        data_211_reg_3568 <= {{layer3_out_dout[727:720]}};
        data_212_reg_3573 <= {{layer3_out_dout[735:728]}};
        data_213_reg_3578 <= {{layer3_out_dout[743:736]}};
        data_214_reg_3583 <= {{layer3_out_dout[751:744]}};
        data_215_reg_3588 <= {{layer3_out_dout[759:752]}};
        data_216_reg_3593 <= {{layer3_out_dout[767:760]}};
        data_217_reg_3598 <= {{layer3_out_dout[775:768]}};
        data_218_reg_3603 <= {{layer3_out_dout[783:776]}};
        data_219_reg_3608 <= {{layer3_out_dout[791:784]}};
        data_220_reg_3613 <= {{layer3_out_dout[799:792]}};
        data_221_reg_3618 <= {{layer3_out_dout[807:800]}};
        data_222_reg_3623 <= {{layer3_out_dout[815:808]}};
        data_223_reg_3628 <= {{layer3_out_dout[823:816]}};
        data_224_reg_3633 <= {{layer3_out_dout[831:824]}};
        data_225_reg_3638 <= {{layer3_out_dout[839:832]}};
        data_226_reg_3643 <= {{layer3_out_dout[847:840]}};
        data_227_reg_3648 <= {{layer3_out_dout[855:848]}};
        data_228_reg_3653 <= {{layer3_out_dout[863:856]}};
        data_229_reg_3658 <= {{layer3_out_dout[871:864]}};
        data_230_reg_3663 <= {{layer3_out_dout[879:872]}};
        data_231_reg_3668 <= {{layer3_out_dout[887:880]}};
        data_232_reg_3673 <= {{layer3_out_dout[895:888]}};
        data_233_reg_3678 <= {{layer3_out_dout[903:896]}};
        data_234_reg_3683 <= {{layer3_out_dout[911:904]}};
        data_235_reg_3688 <= {{layer3_out_dout[919:912]}};
        data_236_reg_3693 <= {{layer3_out_dout[927:920]}};
        data_237_reg_3698 <= {{layer3_out_dout[935:928]}};
        data_238_reg_3703 <= {{layer3_out_dout[943:936]}};
        data_239_reg_3708 <= {{layer3_out_dout[951:944]}};
        data_240_reg_3713 <= {{layer3_out_dout[959:952]}};
        data_241_reg_3718 <= {{layer3_out_dout[967:960]}};
        data_242_reg_3723 <= {{layer3_out_dout[975:968]}};
        data_243_reg_3728 <= {{layer3_out_dout[983:976]}};
        data_244_reg_3733 <= {{layer3_out_dout[991:984]}};
        data_245_reg_3738 <= {{layer3_out_dout[999:992]}};
        data_246_reg_3743 <= {{layer3_out_dout[1007:1000]}};
        data_247_reg_3748 <= {{layer3_out_dout[1015:1008]}};
        data_248_reg_3753 <= {{layer3_out_dout[1023:1016]}};
        data_249_reg_3123 <= {{layer3_out_dout[15:8]}};
        data_reg_3118 <= data_fu_1007_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_10_fu_578 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_11_fu_582 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_12_fu_586 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_13_fu_590 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_14_fu_594 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_15_fu_598 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_16_fu_602 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_17_fu_606 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_18_fu_610 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_19_fu_614 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_19;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_1_fu_542 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_20_fu_618 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_20;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_21_fu_622 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_21;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_22_fu_626 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_22;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_23_fu_630 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_23;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_24_fu_634 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_24;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_25_fu_638 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_25;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_26_fu_642 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_26;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_27_fu_646 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_27;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_28_fu_650 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_28;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_29_fu_654 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_29;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_2_fu_546 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_30_fu_658 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_30;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_31_fu_662 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_31;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_32_fu_666 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_32;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_33_fu_670 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_33;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_34_fu_674 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_34;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_35_fu_678 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_35;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_36_fu_682 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_36;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_37_fu_686 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_37;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_38_fu_690 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_38;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_39_fu_694 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_39;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_3_fu_550 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_40_fu_698 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_40;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_41_fu_702 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_41;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_42_fu_706 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_42;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_43_fu_710 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_43;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_44_fu_714 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_44;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_45_fu_718 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_45;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_46_fu_722 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_46;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_47_fu_726 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_47;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_48_fu_730 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_48;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_49_fu_734 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_49;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_4_fu_554 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_50_fu_738 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_50;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_51_fu_742 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_51;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_52_fu_746 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_52;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_53_fu_750 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_53;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_54_fu_754 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_54;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_55_fu_758 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_55;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_56_fu_762 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_56;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_57_fu_766 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_57;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_58_fu_770 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_58;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_59_fu_774 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_59;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_5_fu_558 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_60_fu_778 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_60;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_61_fu_782 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_61;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_62_fu_786 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_62;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_63_fu_790 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_63;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_6_fu_562 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_7_fu_566 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_8_fu_570 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_9_fu_574 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_9;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        res_fu_538 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_res_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer4_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call195 = ((real_start == 1'b0) | (layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_fu_1007_p1 = layer3_out_dout[7:0];

assign grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start = grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_6_5_3_0_config4_s_fu_807_ap_start_reg;

assign layer4_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_63_fu_790}, {res_62_fu_786}}, {res_61_fu_782}}, {res_60_fu_778}}, {res_59_fu_774}}, {res_58_fu_770}}, {res_57_fu_766}}, {res_56_fu_762}}, {res_55_fu_758}}, {res_54_fu_754}}, {res_53_fu_750}}, {res_52_fu_746}}, {res_51_fu_742}}, {res_50_fu_738}}, {res_49_fu_734}}, {res_48_fu_730}}, {res_47_fu_726}}, {res_46_fu_722}}, {res_45_fu_718}}, {res_44_fu_714}}, {res_43_fu_710}}, {res_42_fu_706}}, {res_41_fu_702}}, {res_40_fu_698}}, {res_39_fu_694}}, {res_38_fu_690}}, {res_37_fu_686}}, {res_36_fu_682}}, {res_35_fu_678}}, {res_34_fu_674}}, {res_33_fu_670}}, {res_32_fu_666}}, {res_31_fu_662}}, {res_30_fu_658}}, {res_29_fu_654}}, {res_28_fu_650}}, {res_27_fu_646}}, {res_26_fu_642}}, {res_25_fu_638}}, {res_24_fu_634}}, {res_23_fu_630}}, {res_22_fu_626}}, {res_21_fu_622}}, {res_20_fu_618}}, {res_19_fu_614}}, {res_18_fu_610}}, {res_17_fu_606}}, {res_16_fu_602}}, {res_15_fu_598}}, {res_14_fu_594}}, {res_13_fu_590}}, {res_12_fu_586}}, {res_11_fu_582}}, {res_10_fu_578}}, 
    {res_9_fu_574}}, {res_8_fu_570}}, {res_7_fu_566}}, {res_6_fu_562}}, {res_5_fu_558}}, {res_4_fu_554}}, {res_3_fu_550}}, {res_2_fu_546}}, {res_1_fu_542}}, {res_fu_538}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_128u_array_ap_fixed_18_6_5_3_0_64u_config4_s
