// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer11_cpy2_dout,
        layer11_cpy2_empty_n,
        layer11_cpy2_read,
        layer11_cpy2_num_data_valid,
        layer11_cpy2_fifo_cap,
        layer10_out_TDATA,
        layer10_out_TVALID,
        layer10_out_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer11_cpy2_dout;
input   layer11_cpy2_empty_n;
output   layer11_cpy2_read;
input  [1:0] layer11_cpy2_num_data_valid;
input  [1:0] layer11_cpy2_fifo_cap;
output  [31:0] layer10_out_TDATA;
output   layer10_out_TVALID;
input   layer10_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer11_cpy2_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer11_cpy2_blk_n;
reg    layer10_out_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [7:0] data_fu_205_p1;
reg   [7:0] data_reg_556;
reg    ap_block_state1;
reg   [7:0] data_123_reg_561;
reg   [7:0] data_93_reg_566;
reg   [7:0] data_94_reg_571;
reg   [7:0] data_95_reg_576;
reg   [7:0] data_96_reg_581;
reg   [7:0] data_97_reg_586;
reg   [7:0] data_98_reg_591;
reg   [7:0] data_99_reg_596;
reg   [7:0] data_100_reg_601;
reg   [7:0] data_101_reg_606;
reg   [7:0] data_102_reg_611;
reg   [7:0] data_103_reg_616;
reg   [7:0] data_104_reg_621;
reg   [7:0] data_105_reg_626;
reg   [7:0] data_106_reg_631;
reg   [7:0] data_107_reg_636;
reg   [7:0] data_108_reg_641;
reg   [7:0] data_109_reg_646;
reg   [7:0] data_110_reg_651;
reg   [7:0] data_111_reg_656;
reg   [7:0] data_112_reg_661;
reg   [7:0] data_113_reg_666;
reg   [7:0] data_114_reg_671;
reg   [7:0] data_115_reg_676;
reg   [7:0] data_116_reg_681;
reg   [7:0] data_117_reg_686;
reg   [7:0] data_118_reg_691;
reg   [7:0] data_119_reg_696;
reg   [7:0] data_120_reg_701;
reg   [7:0] data_121_reg_706;
reg   [7:0] data_122_reg_711;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg;
reg    ap_block_state1_ignore_call35;
wire    regslice_both_layer10_out_U_apdone_blk;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [31:0] layer10_out_TDATA_int_regslice;
reg    layer10_out_TVALID_int_regslice;
wire    layer10_out_TREADY_int_regslice;
wire    regslice_both_layer10_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg = 1'b0;
end

myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready),
    .data_0_val(data_reg_556),
    .data_1_val(data_123_reg_561),
    .data_2_val(data_93_reg_566),
    .data_3_val(data_94_reg_571),
    .data_4_val(data_95_reg_576),
    .data_5_val(data_96_reg_581),
    .data_6_val(data_97_reg_586),
    .data_7_val(data_98_reg_591),
    .data_8_val(data_99_reg_596),
    .data_9_val(data_100_reg_601),
    .data_10_val(data_101_reg_606),
    .data_11_val(data_102_reg_611),
    .data_12_val(data_103_reg_616),
    .data_13_val(data_104_reg_621),
    .data_14_val(data_105_reg_626),
    .data_15_val(data_106_reg_631),
    .data_16_val(data_107_reg_636),
    .data_17_val(data_108_reg_641),
    .data_18_val(data_109_reg_646),
    .data_19_val(data_110_reg_651),
    .data_20_val(data_111_reg_656),
    .data_21_val(data_112_reg_661),
    .data_22_val(data_113_reg_666),
    .data_23_val(data_114_reg_671),
    .data_24_val(data_115_reg_676),
    .data_25_val(data_116_reg_681),
    .data_26_val(data_117_reg_686),
    .data_27_val(data_118_reg_691),
    .data_28_val(data_119_reg_696),
    .data_29_val(data_120_reg_701),
    .data_30_val(data_121_reg_706),
    .data_31_val(data_122_reg_711),
    .ap_return(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return)
);

myproject_regslice_both #(
    .DataWidth( 32 ))
regslice_both_layer10_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer10_out_TDATA_int_regslice),
    .vld_in(layer10_out_TVALID_int_regslice),
    .ack_in(layer10_out_TREADY_int_regslice),
    .data_out(layer10_out_TDATA),
    .vld_out(regslice_both_layer10_out_U_vld_out),
    .ack_out(layer10_out_TREADY),
    .apdone_blk(regslice_both_layer10_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call35) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_100_reg_601 <= {{layer11_cpy2_dout[79:72]}};
        data_101_reg_606 <= {{layer11_cpy2_dout[87:80]}};
        data_102_reg_611 <= {{layer11_cpy2_dout[95:88]}};
        data_103_reg_616 <= {{layer11_cpy2_dout[103:96]}};
        data_104_reg_621 <= {{layer11_cpy2_dout[111:104]}};
        data_105_reg_626 <= {{layer11_cpy2_dout[119:112]}};
        data_106_reg_631 <= {{layer11_cpy2_dout[127:120]}};
        data_107_reg_636 <= {{layer11_cpy2_dout[135:128]}};
        data_108_reg_641 <= {{layer11_cpy2_dout[143:136]}};
        data_109_reg_646 <= {{layer11_cpy2_dout[151:144]}};
        data_110_reg_651 <= {{layer11_cpy2_dout[159:152]}};
        data_111_reg_656 <= {{layer11_cpy2_dout[167:160]}};
        data_112_reg_661 <= {{layer11_cpy2_dout[175:168]}};
        data_113_reg_666 <= {{layer11_cpy2_dout[183:176]}};
        data_114_reg_671 <= {{layer11_cpy2_dout[191:184]}};
        data_115_reg_676 <= {{layer11_cpy2_dout[199:192]}};
        data_116_reg_681 <= {{layer11_cpy2_dout[207:200]}};
        data_117_reg_686 <= {{layer11_cpy2_dout[215:208]}};
        data_118_reg_691 <= {{layer11_cpy2_dout[223:216]}};
        data_119_reg_696 <= {{layer11_cpy2_dout[231:224]}};
        data_120_reg_701 <= {{layer11_cpy2_dout[239:232]}};
        data_121_reg_706 <= {{layer11_cpy2_dout[247:240]}};
        data_122_reg_711 <= {{layer11_cpy2_dout[255:248]}};
        data_123_reg_561 <= {{layer11_cpy2_dout[15:8]}};
        data_93_reg_566 <= {{layer11_cpy2_dout[23:16]}};
        data_94_reg_571 <= {{layer11_cpy2_dout[31:24]}};
        data_95_reg_576 <= {{layer11_cpy2_dout[39:32]}};
        data_96_reg_581 <= {{layer11_cpy2_dout[47:40]}};
        data_97_reg_586 <= {{layer11_cpy2_dout[55:48]}};
        data_98_reg_591 <= {{layer11_cpy2_dout[63:56]}};
        data_99_reg_596 <= {{layer11_cpy2_dout[71:64]}};
        data_reg_556 <= data_fu_205_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer10_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        layer10_out_TDATA_blk_n = layer10_out_TREADY_int_regslice;
    end else begin
        layer10_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer10_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer10_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer10_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_cpy2_blk_n = layer11_cpy2_empty_n;
    end else begin
        layer11_cpy2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_cpy2_read = 1'b1;
    end else begin
        layer11_cpy2_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((layer10_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (layer11_cpy2_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call35 = ((ap_start == 1'b0) | (layer11_cpy2_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((layer10_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer10_out_U_apdone_blk == 1'b1));
end

assign data_fu_205_p1 = layer11_cpy2_dout[7:0];

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_start_reg;

assign layer10_out_TDATA_int_regslice = $signed(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_32_16_5_3_0_config10_s_fu_167_ap_return);

assign layer10_out_TVALID = regslice_both_layer10_out_U_vld_out;

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_32_16_5_3_0_1u_config10_s
